import SwiftUI
import SwiftData
import PhotosUI
import UIKit

/// Structured garment capture: pick → crop/edit → details.
struct AddGarmentView: View {
    @Environment(\.modelContext) private var context
    @Environment(\.dismiss) private var dismiss

    @Query(sort: \Brand.name, order: .forward) private var brands: [Brand]

    private enum FlowState: Equatable {
        case selectImage
        case enterDetails
        case batchReview
    }

    @State private var flowState: FlowState = .selectImage

    // MARK: Batch upload state

    struct BatchItem: Identifiable {
        enum Status: Equatable {
            case processing
            case ready
            case needsCategory
        }

        let id = UUID()
        let original: UIImage
        var display: UIImage?
        var status: Status = .processing
        var category: Category?
        var itemType: ItemType?
        var colorTags: [ColorTag] = []
        var aiConfidence: Float = 0
        var usedAI = false
    }

    @State private var batchItems: [BatchItem] = []
    @State private var isSavingBatch = false

    // MARK: Label scan state

    @State private var showLabelScanner = false
    @State private var isScanningLabel = false
    @State private var labelScanMessage: String?
    /// Materials read off the physical care label — user-verified facts.
    @State private var scannedMaterials: [MaterialTag] = []

    // Structured fields
    @State private var category: Category? = nil
    @State private var itemType: ItemType? = nil
    @State private var brand = ""
    @State private var colorTags: [ColorTag] = []
    @State private var userTitleOverride: String? = nil
    @State private var isEditingTitle = false
    @State private var isSuggestingName = false
    /// Provenance: attribute fields the user touched by hand. Enrichment
    /// (type defaults / on-device AI) never overwrites these.
    @State private var userEditedFields: Set<String> = []
    /// Which detail card is expanded from a quick-chip tap (nil = collapsed).
    @State private var focusedSection: FocusSection? = nil
    /// Reveals the full detail form (brand, size, season...) for power users.
    @State private var showAllDetails = false

    private enum FocusSection {
        case essentials
        case colors
        case attributes
    }
    @State private var patternTag: PatternTag? = nil
    @State private var fitTag: FitTag? = nil
    @State private var sizeOption: SizeOption? = nil
    @State private var seasonSuitability: SeasonSuitability? = nil
    @State private var minTempC: Double? = nil
    @State private var maxTempC: Double? = nil
    @State private var warmth = 3
    @State private var thermalWarmthOverride: Int?
    @State private var thermalBreathabilityOverride: Int?
    @State private var formality = 3
    @State private var love = 50

    // Image
    @State private var selectedImage: UIImage?
    @State private var originalPickedImage: UIImage?
    @State private var pendingCropImage: UIImage?
    @State private var showCropper = false
    @State private var savedImagePath: String?
    @State private var savedThumbnailPath: String?
    @State private var savedOriginalImagePath: String?

    // AI
    @State private var isAnalyzing = false
    @State private var aiConfidence: Float = 0
    @State private var didApplyAISuggestions = false
    @State private var aiSuggestedCategory: Category?
    @State private var aiSuggestedItemType: ItemType?
    @State private var aiSuggestedColors: [ColorTag] = []

    // UI
    @State private var showCamera = false
    @State private var showPhotoPicker = false
    @State private var showBarcodeScanner = false
    @State private var showProductLinkSheet = false
    @State private var productLinkText = ""
    @State private var isLookingUpBarcode = false
    @State private var isFetchingProductPage = false
    /// Product lookup filled the form but no image came back — user still needs a photo.
    @State private var barcodeNeedsPhoto = false
    /// Ignores late image downloads from a previous barcode scan.
    @State private var barcodeLookupGeneration = UUID()
    @State private var showSuccess = false
    @State private var showAdvancedOptions = false
    @State private var errorMessage: String?

    private let feedback = UIImpactFeedbackGenerator(style: .medium)
    private let onSave: ((Garment) -> Void)?

    init(initialCategory: Category? = nil, onSave: ((Garment) -> Void)? = nil) {
        self.onSave = onSave
        _category = State(initialValue: initialCategory)
    }

    private var autoGeneratedTitle: String {
        var parts: [String] = []
        if let primaryColor = colorTags.first {
            parts.append(primaryColor.title)
        }
        if let type = itemType {
            parts.append(type.title.lowercased())
        } else if let cat = category {
            parts.append(cat.title.lowercased())
        }
        var title = parts.joined(separator: " ")
        if let first = title.first {
            title = first.uppercased() + title.dropFirst()
        }
        if !brand.isEmpty {
            title += " — \(brand)"
        }
        return title.isEmpty ? String(localized: "add_garment_new_item") : title
    }

    private var displayTitle: String {
        if let override = userTitleOverride, !override.isEmpty {
            return override
        }
        return autoGeneratedTitle
    }

    private var canSave: Bool { category != nil && selectedImage != nil }
    /// Details are ready but wardrobe photo is still missing (typical after barcode/QR).
    private var needsPhotoBeforeSave: Bool { category != nil && selectedImage == nil }

    private var brandSuggestions: [Brand] {
        let text = brand.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return [] }
        return Array(brands.filter { $0.name.localizedCaseInsensitiveContains(text) }.prefix(5))
    }

    private var shouldShowAddBrand: Bool {
        let text = brand.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return false }
        return !brands.contains(where: { $0.name.lowercased() == text.lowercased() })
    }

    private var shouldShowFit: Bool {
        guard let cat = category else { return false }
        return cat == .top || cat == .bottom
    }

    private var shouldShowSize: Bool {
        guard let cat = category else { return false }
        return cat == .top || cat == .bottom || cat == .shoes
    }

    private var sizeOptions: [SizeOption] {
        guard let cat = category else { return [] }
        return SizeOption.options(for: cat)
    }

    private var categoryColumns: [GridItem] {
        Array(repeating: GridItem(.flexible(minimum: 0), spacing: DS.Spacing.xs), count: 3)
    }

    // MARK: - Body

    var body: some View {
        NavigationStack {
            Group {
                switch flowState {
                case .selectImage:
                    imageSelectionView
                case .enterDetails:
                    detailsFormView
                case .batchReview:
                    batchReviewView
                }
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .navigationTitle(navigationTitle)
            .minimalCollapsingNavBar()
            .withLocalAppBackdrop()
            .toolbar { toolbarContent }
            .alert(String(localized: "add_garment_success_title"), isPresented: $showSuccess) {
                Button(String(localized: "action_done")) { resetAndDismiss() }
            } message: {
                Text(String(localized: "add_garment_success_message"))
            }
            .alert(String(localized: "error_title"), isPresented: Binding(
                get: { errorMessage != nil },
                set: { if !$0 { errorMessage = nil } }
            )) {
                Button(String(localized: "action_confirm"), role: .cancel) {}
            } message: {
                Text(errorMessage ?? String(localized: "error_generic"))
            }
            .sheet(isPresented: $showPhotoPicker) {
                MultiPhotoPickerWrapper(selectionLimit: 10) { images in
                    if images.count == 1, let image = images.first {
                        processPickedImage(image)
                    } else {
                        startBatch(with: images)
                    }
                }
            }
            .sheet(isPresented: $showCamera) {
                CameraPickerWrapper { image in
                    processPickedImage(image)
                }
            }
            .sheet(isPresented: $showLabelScanner) {
                CameraPickerWrapper { image in
                    handleLabelScan(image)
                }
            }
            .fullScreenCover(isPresented: $showBarcodeScanner) {
                BarcodeScannerScreen(
                    onCode: { code in
                        showBarcodeScanner = false
                        lookupBarcode(code)
                    },
                    onCancel: {
                        showBarcodeScanner = false
                    }
                )
            }
            .sheet(isPresented: $showProductLinkSheet) {
                productLinkSheet
            }
            .fullScreenCover(isPresented: $showCropper) {
                if let pendingCropImage {
                    ImageCropperView(
                        image: pendingCropImage,
                        initialAspect: .portrait34,
                        onCancel: {
                            showCropper = false
                            self.pendingCropImage = nil
                        },
                        onDone: { cropped in
                            showCropper = false
                            self.pendingCropImage = nil
                            confirmCroppedImage(cropped, original: originalPickedImage ?? cropped)
                        }
                    )
                }
            }
            .onAppear {
                BrandStore.syncFromGarments(context: context)
            }
        }
    }

    private var navigationTitle: String {
        switch flowState {
        case .selectImage: return String(localized: "nav_add_item")
        case .enterDetails: return String(localized: "add_garment_details_title")
        case .batchReview: return String(localized: "batch_review_title")
        }
    }

    @ToolbarContentBuilder
    private var toolbarContent: some ToolbarContent {
        if flowState == .enterDetails {
            ToolbarItem(placement: .cancellationAction) {
                Button(String(localized: "action_back")) {
                    withAnimation(DS.Animation.standard) {
                        flowState = .selectImage
                    }
                }
            }
        } else if flowState == .batchReview {
            ToolbarItem(placement: .cancellationAction) {
                Button(String(localized: "action_back")) {
                    withAnimation(DS.Animation.standard) {
                        batchItems = []
                        flowState = .selectImage
                    }
                }
                .disabled(isSavingBatch)
            }
        }
    }

    // MARK: - Select image

    private var imageSelectionView: some View {
        ZStack {
            VStack(spacing: DS.Spacing.xl) {
                Spacer(minLength: DS.Spacing.lg)

                ZStack {
                    Circle()
                        .fill(Color.accentColor.opacity(0.12))
                        .frame(width: 112, height: 112)
                    Image(systemName: "camera.viewfinder")
                        .font(.system(size: DS.IconSize.xxl, weight: .light))
                        .foregroundStyle(Color.accentColor)
                }

                VStack(spacing: DS.Spacing.sm) {
                    Text(String(localized: "add_garment_hero_title"))
                        .font(.title2.bold())
                        .multilineTextAlignment(.center)
                    Text(String(localized: "add_garment_hero_subtitle"))
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .frame(maxWidth: .infinity)
                .padding(.horizontal, DS.Spacing.md)

                VStack(spacing: DS.Spacing.sm) {
                    Button {
                        DS.haptic(0.6)
                        showCamera = true
                    } label: {
                        Label(String(localized: "add_garment_take_photo"), systemImage: "camera.fill")
                    }
                    .dsPrimaryButton()
                    .disabled(isLookingUpBarcode)

                    Button {
                        DS.haptic(0.5)
                        showBarcodeScanner = true
                    } label: {
                        Label(String(localized: "add_garment_scan_barcode"), systemImage: "barcode.viewfinder")
                            .frame(maxWidth: .infinity)
                    }
                    .dsSecondaryButton()
                    .disabled(isLookingUpBarcode)

                    Button {
                        DS.haptic(0.5)
                        productLinkText = UIPasteboard.general.string ?? ""
                        showProductLinkSheet = true
                    } label: {
                        Label(String(localized: "add_garment_paste_link"), systemImage: "link")
                            .frame(maxWidth: .infinity)
                    }
                    .dsSecondaryButton()
                    .disabled(isLookingUpBarcode)

                    Button {
                        DS.haptic(0.5)
                        showPhotoPicker = true
                    } label: {
                        Label(String(localized: "add_garment_choose_library"), systemImage: "photo.on.rectangle")
                            .frame(maxWidth: .infinity)
                    }
                    .dsSecondaryButton()
                    .disabled(isLookingUpBarcode)
                }
                .frame(maxWidth: .infinity)
                .padding(.horizontal, DS.Spacing.xl)

                Text(String(localized: "add_garment_crop_hint"))
                    .font(.caption)
                    .foregroundStyle(.tertiary)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, DS.Spacing.lg)

                Spacer()
                Spacer()
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .padding(.horizontal, DS.Spacing.md)
            .opacity(isLookingUpBarcode ? 0.45 : 1)

            if isLookingUpBarcode {
                VStack(spacing: DS.Spacing.sm) {
                    ProgressView()
                    Text(String(localized: isFetchingProductPage ? "webpage_looking_up" : "barcode_looking_up"))
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
                .padding(DS.Spacing.lg)
                .background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: DS.Radius.card, style: .continuous))
            }
        }
    }

    private var productLinkSheet: some View {
        NavigationStack {
            Form {
                Section {
                    TextField(String(localized: "add_garment_paste_link_placeholder"), text: $productLinkText)
                        .textInputAutocapitalization(.never)
                        .keyboardType(.URL)
                        .autocorrectionDisabled()
                        .textContentType(.URL)
                } footer: {
                    Text(String(localized: "add_garment_paste_link_hint"))
                }

                Section {
                    Button {
                        if let clipped = UIPasteboard.general.string?.trimmingCharacters(in: .whitespacesAndNewlines),
                           !clipped.isEmpty {
                            productLinkText = clipped
                        }
                    } label: {
                        Label(String(localized: "add_garment_paste_from_clipboard"), systemImage: "doc.on.clipboard")
                    }
                }
            }
            .navigationTitle(String(localized: "add_garment_paste_link"))
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button(String(localized: "action_cancel")) {
                        showProductLinkSheet = false
                    }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button(String(localized: "add_garment_fetch_link")) {
                        let link = productLinkText
                        showProductLinkSheet = false
                        lookupProductLink(link)
                    }
                    .disabled(productLinkText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                }
            }
        }
        .presentationDetents([.medium])
    }

    // MARK: - Details

    private var draftThermalProfile: GarmentThermalProfile {
        GarmentThermalProfile(
            warmth: warmth, itemType: itemType, materials: scannedMaterials,
            fit: fitTag,
            estimatedFields: userEditedFields.contains(ItemTypeDefaults.FieldKey.warmth) ? [] : ["warmth"],
            warmthOverride: thermalWarmthOverride,
            breathabilityOverride: thermalBreathabilityOverride
        )
    }

    private var detailsFormView: some View {
        ScrollView {
            VStack(spacing: DS.Spacing.md) {
                if needsPhotoBeforeSave {
                    barcodeNeedsPhotoBanner
                }
                heroCard
                quickChipsCard
                ThermalProfileEditor(
                    profile: draftThermalProfile,
                    warmthOverride: $thermalWarmthOverride,
                    breathabilityOverride: $thermalBreathabilityOverride
                )
                if showAllDetails || focusedSection == .essentials {
                    essentialsCard
                }
                if showAllDetails || focusedSection == .colors {
                    colorSection
                }
                if showAllDetails || focusedSection == .attributes {
                    attributesSection
                }
                if showAllDetails {
                    if shouldShowFit || shouldShowSize {
                        fitSizeSection
                    }
                    brandSection
                    seasonSection
                    advancedSection
                } else {
                    moreDetailsButton
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, DS.Spacing.md)
            .padding(.top, DS.Spacing.sm)
            .padding(.bottom, DS.Spacing.xxl)
        }
        .scrollDismissesKeyboard(.interactively)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .safeAreaInset(edge: .bottom, spacing: 0) {
            stickySaveBar
        }
    }

    private var stickySaveBar: some View {
        VStack(spacing: 0) {
            Divider().opacity(0.35)
            Button {
                feedback.impactOccurred(intensity: 1.0)
                if needsPhotoBeforeSave {
                    showCamera = true
                } else {
                    saveGarment()
                }
            } label: {
                Text(String(localized: needsPhotoBeforeSave
                    ? "barcode_found_needs_photo_action"
                    : "garment_add_title"))
                    .font(.headline)
                    .frame(maxWidth: .infinity)
            }
            .dsPrimaryButton()
            .disabled(isAnalyzing || category == nil)
            .padding(.horizontal, DS.Spacing.md)
            .padding(.top, DS.Spacing.sm)
            .padding(.bottom, DS.Spacing.md)
        }
        .background(.ultraThinMaterial)
    }

    private var barcodeNeedsPhotoBanner: some View {
        Button {
            showCamera = true
        } label: {
            Label(String(localized: "barcode_found_needs_photo"), systemImage: "camera.fill")
                .font(.subheadline.weight(.medium))
                .foregroundStyle(.primary)
                .padding(DS.Spacing.md)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color.accentColor.opacity(0.12), in: RoundedRectangle(cornerRadius: DS.Radius.card, style: .continuous))
        }
        .buttonStyle(.plain)
    }

    // MARK: - Quick confirmation chips

    /// The heart of the frictionless flow: everything AI/defaults filled is
    /// summarized as tappable chips. If it looks right — just save. Tapping a
    /// chip expands only that editing card.
    private var quickChipsCard: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: DS.Spacing.xs) {
                    quickChip(
                        icon: category?.icon ?? "square.grid.2x2",
                        title: itemType?.title ?? category?.title ?? String(localized: "add_garment_chip_choose_category"),
                        isFocused: focusedSection == .essentials,
                        needsAttention: category == nil
                    ) {
                        toggleFocus(.essentials)
                    }
                    quickChip(
                        icon: "paintpalette",
                        title: colorChipTitle,
                        isFocused: focusedSection == .colors,
                        needsAttention: false
                    ) {
                        toggleFocus(.colors)
                    }
                    quickChip(
                        icon: "briefcase",
                        title: String(format: NSLocalizedString("add_garment_chip_formality_format", comment: ""), formality),
                        isFocused: focusedSection == .attributes,
                        needsAttention: false
                    ) {
                        toggleFocus(.attributes)
                    }
                }
            }

            Text(category == nil
                ? String(localized: "add_garment_chips_hint_missing_category")
                : String(localized: "add_garment_chips_hint"))
                .font(.caption2)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var colorChipTitle: String {
        if colorTags.isEmpty {
            return String(localized: "add_garment_chip_colors")
        }
        return colorTags.prefix(2).map(\.title).joined(separator: ", ")
    }

    private func quickChip(
        icon: String,
        title: String,
        isFocused: Bool,
        needsAttention: Bool,
        action: @escaping () -> Void
    ) -> some View {
        Button(action: action) {
            HStack(spacing: 6) {
                Image(systemName: icon)
                    .font(.caption)
                Text(title)
                    .font(.caption.weight(.semibold))
                    .lineLimit(1)
                Image(systemName: isFocused ? "chevron.up" : "chevron.down")
                    .font(.caption2.weight(.semibold))
                    .foregroundStyle(.tertiary)
            }
            .padding(.horizontal, DS.Spacing.sm)
            .padding(.vertical, DS.Spacing.xs)
            .foregroundStyle(needsAttention ? Color.accentColor : (isFocused ? Color.accentColor : .primary))
            .frame(minHeight: 44)
            .background(
                Capsule(style: .continuous)
                    .fill(isFocused || needsAttention
                        ? Color.accentColor.opacity(0.14)
                        : Color(.secondarySystemBackground).opacity(0.45))
            )
            .overlay(
                Capsule(style: .continuous)
                    .strokeBorder(
                        needsAttention || isFocused ? Color.accentColor.opacity(0.55) : Color.white.opacity(0.10),
                        lineWidth: 1
                    )
            )
        }
        .buttonStyle(.plain)
    }

    private func toggleFocus(_ section: FocusSection) {
        DS.haptic(0.35)
        withAnimation(DS.Animation.standard) {
            focusedSection = (focusedSection == section) ? nil : section
        }
    }

    private var moreDetailsButton: some View {
        Button {
            DS.haptic(0.35)
            withAnimation(DS.Animation.standard) {
                showAllDetails = true
                focusedSection = nil
            }
        } label: {
            Label(String(localized: "add_garment_more_details"), systemImage: "slider.horizontal.3")
                .font(.subheadline.weight(.medium))
                .frame(maxWidth: .infinity)
        }
        .dsSecondaryButton()
    }

    // MARK: - Batch review

    private var batchReadyCount: Int {
        batchItems.filter { $0.status != .processing && $0.category != nil }.count
    }

    private var batchProcessingCount: Int {
        batchItems.filter { $0.status == .processing }.count
    }

    private var batchReviewView: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: DS.Spacing.md) {
                Text(batchProcessingCount > 0
                    ? String(format: NSLocalizedString("batch_processing_status_format", comment: ""), batchProcessingCount)
                    : String(localized: "batch_review_hint"))
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)

                LazyVGrid(columns: [GridItem(.adaptive(minimum: 150), spacing: DS.Spacing.sm)], spacing: DS.Spacing.sm) {
                    ForEach(batchItems) { item in
                        batchItemCard(item)
                    }
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, DS.Spacing.md)
            .padding(.top, DS.Spacing.sm)
            .padding(.bottom, DS.Spacing.xxl)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .safeAreaInset(edge: .bottom, spacing: 0) {
            batchSaveBar
        }
    }

    private var batchSaveBar: some View {
        VStack(spacing: 0) {
            Divider().opacity(0.35)
            Button {
                feedback.impactOccurred(intensity: 1.0)
                saveBatch()
            } label: {
                if isSavingBatch {
                    ProgressView()
                        .frame(maxWidth: .infinity)
                } else {
                    Text(String(format: NSLocalizedString("batch_save_all_format", comment: ""), batchReadyCount))
                        .font(.headline)
                        .frame(maxWidth: .infinity)
                }
            }
            .dsPrimaryButton()
            .disabled(batchReadyCount == 0 || isSavingBatch)
            .padding(.horizontal, DS.Spacing.md)
            .padding(.top, DS.Spacing.sm)
            .padding(.bottom, DS.Spacing.md)
        }
        .background(.ultraThinMaterial)
    }

    @ViewBuilder
    private func batchItemCard(_ item: BatchItem) -> some View {
        VStack(spacing: DS.Spacing.xs) {
            ZStack {
                RoundedRectangle(cornerRadius: DS.Radius.sm, style: .continuous)
                    .fill(Color(.secondarySystemBackground).opacity(0.45))

                Image(uiImage: item.display ?? item.original)
                    .resizable()
                    .scaledToFill()
                    .frame(minWidth: 0, maxWidth: .infinity, minHeight: 0, maxHeight: .infinity)
                    .clipped()

                if item.status == .processing {
                    Color.black.opacity(0.22)
                    ProgressView()
                        .tint(.white)
                }
            }
            .aspectRatio(DS.AspectRatio.garmentTile, contentMode: .fit)
            .clipShape(RoundedRectangle(cornerRadius: DS.Radius.sm, style: .continuous))
            .overlay(alignment: .topTrailing) {
                Button {
                    withAnimation(DS.Animation.standard) {
                        batchItems.removeAll { $0.id == item.id }
                        if batchItems.isEmpty {
                            flowState = .selectImage
                        }
                    }
                } label: {
                    Image(systemName: "xmark.circle.fill")
                        .font(.title3)
                        .symbolRenderingMode(.palette)
                        .foregroundStyle(.white, .black.opacity(0.45))
                }
                .buttonStyle(.plain)
                .padding(6)
                .accessibilityLabel(String(localized: "batch_item_remove"))
                .disabled(isSavingBatch)
            }

            // Category chip: AI result, or a menu to pick one when missing.
            Menu {
                ForEach(Category.allCases) { cat in
                    Button {
                        setBatchCategory(cat, for: item.id)
                    } label: {
                        Label(cat.title, systemImage: cat.icon)
                    }
                }
            } label: {
                HStack(spacing: 4) {
                    Image(systemName: item.category?.icon ?? "questionmark.circle")
                        .font(.caption2)
                    Text(item.itemType?.title ?? item.category?.title ?? String(localized: "batch_needs_category"))
                        .font(.caption2.weight(.semibold))
                        .lineLimit(1)
                    Image(systemName: "chevron.down")
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                }
                .padding(.horizontal, DS.Spacing.sm)
                .padding(.vertical, 5)
                .foregroundStyle(item.category == nil ? Color.accentColor : .primary)
                .background(
                    Capsule(style: .continuous)
                        .fill(item.category == nil
                            ? Color.accentColor.opacity(0.14)
                            : Color(.secondarySystemBackground).opacity(0.45))
                )
            }
            .disabled(item.status == .processing || isSavingBatch)
        }
        .padding(DS.Spacing.xs)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: false)
    }

    private func setBatchCategory(_ category: Category, for id: UUID) {
        guard let index = batchItems.firstIndex(where: { $0.id == id }) else { return }
        batchItems[index].category = category
        if let type = batchItems[index].itemType, !category.itemTypes.contains(type) {
            batchItems[index].itemType = nil
        }
        if batchItems[index].status == .needsCategory {
            batchItems[index].status = .ready
        }
        DS.haptic(0.35)
    }

    private func startBatch(with images: [UIImage]) {
        batchItems = images.map { BatchItem(original: $0) }
        withAnimation(DS.Animation.standard) {
            flowState = .batchReview
        }
        // Serial analysis keeps memory bounded and the UI responsive; each
        // finished item flips from spinner to reviewable card.
        Task {
            for item in batchItems {
                guard flowState == .batchReview else { return }
                let suggestion = await AutoFillService.suggest(from: item.original)
                guard let index = batchItems.firstIndex(where: { $0.id == item.id }) else { continue }
                withAnimation(DS.Animation.standard) {
                    batchItems[index].display = suggestion.displayImage
                    batchItems[index].category = suggestion.category
                    batchItems[index].itemType = suggestion.itemType
                    batchItems[index].colorTags = suggestion.colorTags
                    batchItems[index].aiConfidence = suggestion.confidence
                    batchItems[index].usedAI = suggestion.category != nil || !suggestion.colorTags.isEmpty
                    batchItems[index].status = suggestion.category == nil ? .needsCategory : .ready
                }
            }
        }
    }

    private func saveBatch() {
        let itemsToSave = batchItems.filter { $0.status != .processing && $0.category != nil }
        guard !itemsToSave.isEmpty, !isSavingBatch else { return }
        isSavingBatch = true

        var savedGarments: [Garment] = []
        let profile = CurrentUser.activeProfile(in: context, createIfNeeded: true)

        for item in itemsToSave {
            guard let category = item.category else { continue }
            let display = item.display ?? item.original

            var imagePath: String?
            var originalPath: String?
            var thumbnailPath: String?
            if let png = display.pngData() {
                imagePath = try? ImageStore.save(data: png, preferredExt: "png")
            } else if let jpeg = display.jpegData(compressionQuality: 0.9) {
                imagePath = try? ImageStore.save(data: jpeg, preferredExt: "jpg")
            }
            if let jpeg = item.original.jpegData(compressionQuality: 0.9) {
                originalPath = try? ImageStore.save(data: jpeg, preferredExt: "jpg")
            }
            if let imagePath {
                thumbnailPath = ImageStore.generateAndSaveThumbnail(
                    for: imagePath,
                    maxPixelSize: ImageStore.thumbnailMaxPixelSize
                )
            }
            guard imagePath != nil else { continue }

            let garment = Garment(
                category: category,
                itemType: item.itemType,
                colorTags: item.colorTags,
                imagePath: imagePath,
                thumbnailPath: thumbnailPath,
                originalImagePath: originalPath,
                aiSuggestedCategory: item.usedAI ? item.category : nil,
                aiSuggestedItemType: item.usedAI ? item.itemType : nil,
                aiSuggestedColors: item.colorTags.isEmpty ? nil : item.colorTags,
                aiConfidence: item.aiConfidence > 0 ? item.aiConfidence : nil,
                aiProcessedAt: item.usedAI ? Date() : nil
            )
            if let profile {
                garment.ownerID = profile.id
                if !profile.garmentIDs.contains(garment.id) {
                    profile.garmentIDs.append(garment.id)
                }
            }
            // Batch items skip the form entirely — everything beyond the
            // category is enrichment-owned.
            garment.markEnriched([
                ItemTypeDefaults.FieldKey.warmth,
                ItemTypeDefaults.FieldKey.formality
            ])
            GarmentEnrichmentService.applyDefaults(to: garment)
            context.insert(garment)
            savedGarments.append(garment)
        }

        do {
            try context.save()
            for garment in savedGarments {
                if let path = garment.imagePath {
                    CloudKitImageSyncService.shared.enqueueUpload(garmentID: garment.id, imagePath: path)
                }
            }
            Task {
                for garment in savedGarments {
                    await GarmentEnrichmentService.enrichWithAI(garment, context: context)
                }
            }
            NotificationCenter.default.post(name: .garmentAdded, object: nil)
            isSavingBatch = false
            let unsaved = batchItems.filter { candidate in
                !itemsToSave.contains { $0.id == candidate.id }
            }
            withAnimation(DS.Animation.standard) {
                batchItems = unsaved
                if unsaved.isEmpty {
                    showSuccess = true
                    flowState = .selectImage
                }
            }
        } catch {
            isSavingBatch = false
            errorMessage = String(
                format: NSLocalizedString("add_garment_save_failed_format", comment: ""),
                error.localizedDescription
            )
        }
    }

    // MARK: - Cards

    private var heroCard: some View {
        VStack(spacing: DS.Spacing.sm) {
            ZStack {
                RoundedRectangle(cornerRadius: DS.Radius.card, style: .continuous)
                    .fill(Color(.secondarySystemBackground).opacity(0.45))

                if let image = selectedImage {
                    Image(uiImage: image)
                        .resizable()
                        .scaledToFill()
                        .frame(minWidth: 0, maxWidth: .infinity, minHeight: 0, maxHeight: .infinity)
                        .clipped()
                } else {
                    VStack(spacing: DS.Spacing.sm) {
                        Image(systemName: "camera.fill")
                            .font(.system(size: 36, weight: .light))
                        Text(String(localized: "barcode_found_needs_photo_action"))
                            .font(.subheadline.weight(.semibold))
                            .multilineTextAlignment(.center)
                    }
                    .foregroundStyle(.secondary)
                    .padding(DS.Spacing.md)
                }

                if isAnalyzing {
                    Color.black.opacity(0.28)
                    analyzingOverlay
                }
            }
            .aspectRatio(DS.AspectRatio.garmentTile, contentMode: .fit)
            .frame(maxWidth: .infinity)
            .frame(maxHeight: 280)
            .clipShape(RoundedRectangle(cornerRadius: DS.Radius.card, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: DS.Radius.card, style: .continuous)
                    .strokeBorder(Color.white.opacity(0.12), lineWidth: 0.6)
            )
            .contentShape(RoundedRectangle(cornerRadius: DS.Radius.card, style: .continuous))
            .onTapGesture {
                guard selectedImage == nil else { return }
                showCamera = true
            }

            HStack(spacing: DS.Spacing.sm) {
                if selectedImage != nil {
                    Button {
                        reopenCropper()
                    } label: {
                        Label(String(localized: "add_garment_edit_photo"), systemImage: "crop")
                            .font(.caption.weight(.semibold))
                    }
                    .buttonStyle(.plain)
                }

                Button {
                    showCamera = true
                } label: {
                    Label(
                        String(localized: selectedImage == nil ? "add_garment_take_photo" : "add_garment_retake"),
                        systemImage: "camera"
                    )
                    .font(.caption.weight(.semibold))
                }
                .buttonStyle(.plain)

                Spacer(minLength: 0)

                Button {
                    showPhotoPicker = true
                } label: {
                    Label(
                        String(localized: selectedImage == nil ? "add_garment_choose_library" : "add_garment_change_photo"),
                        systemImage: "photo"
                    )
                    .font(.caption.weight(.semibold))
                }
                .buttonStyle(.plain)
            }
            .foregroundStyle(.secondary)

            if didApplyAISuggestions {
                Label(
                    String(localized: barcodeNeedsPhoto && selectedImage == nil
                        ? "barcode_details_filled"
                        : "add_garment_ai_filled"),
                    systemImage: "sparkles"
                )
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .fixedSize(horizontal: false, vertical: true)
            }

            titleEditor
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var titleEditor: some View {
        VStack(spacing: DS.Spacing.xs) {
            if isEditingTitle {
                TextField(String(localized: "garment_edit_title"), text: Binding(
                    get: { userTitleOverride ?? autoGeneratedTitle },
                    set: { userTitleOverride = $0 }
                ))
                .textFieldStyle(.plain)
                .dsFieldStyle()
                .multilineTextAlignment(.center)
                .onSubmit { isEditingTitle = false }

                Button(String(localized: "add_garment_use_auto_title")) {
                    userTitleOverride = nil
                    isEditingTitle = false
                }
                .font(.caption)
                .foregroundStyle(.secondary)
            } else {
                Text(displayTitle)
                    .font(.title3.bold())
                    .multilineTextAlignment(.center)
                    .frame(maxWidth: .infinity)
                    .fixedSize(horizontal: false, vertical: true)

                HStack(spacing: DS.Spacing.md) {
                    Button {
                        isEditingTitle = true
                    } label: {
                        Label(String(localized: "add_garment_edit_title"), systemImage: "pencil")
                            .font(.caption)
                    }
                    .foregroundStyle(.secondary)

                    if LookExplanationAvailability.isSupported {
                        Button {
                            suggestNameWithAI()
                        } label: {
                            if isSuggestingName {
                                ProgressView()
                                    .controlSize(.mini)
                            } else {
                                Label(String(localized: "garment_ai_name_suggest"), systemImage: "sparkles")
                                    .font(.caption)
                            }
                        }
                        .foregroundStyle(Color.accentColor)
                        .disabled(isSuggestingName || category == nil)
                        .accessibilityLabel(String(localized: "garment_ai_name_suggest"))
                    }
                }
            }
        }
        .padding(.top, DS.Spacing.xxs)
    }

    private func suggestNameWithAI() {
        guard #available(iOS 26.0, *) else { return }
        guard !isSuggestingName, let category else { return }
        let request = GarmentNameRequest(
            category: category.rawValue,
            itemType: itemType?.rawValue,
            colors: colorTags.prefix(2).map(\.rawValue),
            material: nil,
            pattern: patternTag?.rawValue,
            fit: fitTag?.rawValue,
            brand: brand.isEmpty ? nil : brand.trimmingCharacters(in: .whitespacesAndNewlines),
            languageCode: Locale.current.language.languageCode?.identifier ?? "en"
        )
        isSuggestingName = true
        Task {
            let name = await LookExplanationService.shared.suggestGarmentName(for: request)
            isSuggestingName = false
            if let name {
                userTitleOverride = name
                DS.haptic(0.4)
            }
        }
    }

    private var essentialsCard: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            DSSectionHeader(String(localized: "garment_category"), icon: "square.grid.2x2")

            LazyVGrid(columns: categoryColumns, spacing: DS.Spacing.xs) {
                ForEach(Category.allCases) { cat in
                    Button {
                        feedback.impactOccurred(intensity: 0.5)
                        selectCategory(cat)
                    } label: {
                        VStack(spacing: 6) {
                            Image(systemName: cat.icon)
                                .font(.title3)
                            Text(cat.title)
                                .font(.caption2.weight(.semibold))
                                .lineLimit(1)
                                .minimumScaleFactor(0.8)
                        }
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, DS.Spacing.sm)
                        .foregroundStyle(category == cat ? Color.accentColor : .primary)
                        .background(
                            RoundedRectangle(cornerRadius: DS.Radius.sm, style: .continuous)
                                .fill(category == cat ? Color.accentColor.opacity(0.14) : Color(.secondarySystemBackground).opacity(0.35))
                        )
                        .overlay(
                            RoundedRectangle(cornerRadius: DS.Radius.sm, style: .continuous)
                                .strokeBorder(category == cat ? Color.accentColor.opacity(0.55) : Color.clear, lineWidth: 1)
                        )
                    }
                    .buttonStyle(.plain)
                }
            }

            if let cat = category {
                Text(String(localized: "garment_item_type"))
                    .font(.subheadline.weight(.semibold))
                    .padding(.top, DS.Spacing.xxs)
                ItemTypeSelector(category: cat, selectedType: Binding(
                    get: { itemType },
                    set: {
                        itemType = $0
                        applyTypeDefaultsToState()
                    }
                ))
            }
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var fitSizeSection: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            DSSectionHeader(String(localized: "fit_size_title"), icon: "ruler")
            if shouldShowFit {
                SingleTagPicker(
                    title: String(localized: "fit_label"),
                    allTags: FitTag.allCases,
                    selectedTag: $fitTag,
                    titleForTag: { $0.title }
                )
            }
            if shouldShowSize {
                SingleTagPicker(
                    title: String(localized: "size_label"),
                    allTags: sizeOptions,
                    selectedTag: $sizeOption,
                    titleForTag: { $0.title }
                )
            }
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var colorSection: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            HStack(spacing: DS.Spacing.xs) {
                Image(systemName: "paintpalette")
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(DS.Text.secondary)
                Text(String(localized: "garment_colors"))
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(DS.Text.secondary)
                Spacer(minLength: 0)
                Text(
                    colorTags.isEmpty
                        ? String(localized: "garment_colors_recommended")
                        : String(format: NSLocalizedString("add_garment_colors_selected_format", comment: ""), colorTags.count)
                )
                .font(.caption)
                .foregroundStyle(.secondary)
            }

            ColorTagSelector(selectedColors: $colorTags)

            Text(String(localized: "tag_bilingual_hint"))
                .font(.caption2)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var brandSection: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            HStack {
                DSSectionHeader(String(localized: "garment_brand"), icon: "tag")
                Spacer(minLength: 0)
                Button {
                    DS.haptic(0.4)
                    showLabelScanner = true
                } label: {
                    if isScanningLabel {
                        ProgressView()
                            .controlSize(.mini)
                    } else {
                        Label(String(localized: "label_scan_button"), systemImage: "text.viewfinder")
                            .font(.caption.weight(.semibold))
                    }
                }
                .buttonStyle(.plain)
                .foregroundStyle(Color.accentColor)
                .disabled(isScanningLabel)
            }

            TextField(String(localized: "garment_brand_placeholder"), text: $brand)
                .textFieldStyle(.plain)
                .dsFieldStyle()

            if let labelScanMessage {
                Label(labelScanMessage, systemImage: "text.viewfinder")
                    .font(.caption2)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }

            if !brandSuggestions.isEmpty || shouldShowAddBrand {
                VStack(alignment: .leading, spacing: 6) {
                    ForEach(brandSuggestions, id: \.name) { suggestion in
                        Button {
                            brand = suggestion.name
                        } label: {
                            Text(suggestion.name)
                                .font(.caption)
                        }
                        .buttonStyle(.plain)
                    }
                    if shouldShowAddBrand {
                        Text(String(format: NSLocalizedString("brand_add_suggestion", comment: ""), brand))
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            }
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var seasonSection: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            DSSectionHeader(String(localized: "garment_season"), icon: "leaf")
            SeasonSelector(selectedSeason: Binding(
                get: { seasonSuitability },
                set: {
                    seasonSuitability = $0
                    userEditedFields.insert(ItemTypeDefaults.FieldKey.season)
                }
            ))
            if seasonSuitability != nil {
                DisclosureGroup(String(localized: "garment_temperature_range")) {
                    TemperatureRangeSlider(
                        minTemp: $minTempC,
                        maxTemp: $maxTempC,
                        defaultRange: seasonSuitability?.defaultTempRange ?? (10, 25)
                    )
                }
                .font(.subheadline)
            }
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var attributesSection: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.md) {
            DSSectionHeader(String(localized: "garment_attributes"), icon: "slider.horizontal.3")
            attributeRow(
                icon: "briefcase",
                title: String(localized: "garment_formality"),
                value: formality,
                tint: .accentColor
            ) {
                Stepper(String(localized: "garment_formality"), value: Binding(
                    get: { formality },
                    set: {
                        formality = $0
                        userEditedFields.insert(ItemTypeDefaults.FieldKey.formality)
                    }
                ), in: 1...5)
                    .labelsHidden()
                    .controlSize(.small)
            }
            VStack(alignment: .leading, spacing: DS.Spacing.xs) {
                HStack {
                    Image(systemName: "heart.fill")
                        .foregroundStyle(.pink)
                    Text(String(localized: "garment_love"))
                        .font(.subheadline.weight(.medium))
                    Spacer()
                    Text("\(love)%")
                        .font(.caption.bold())
                        .foregroundStyle(.pink)
                }
                Slider(value: Binding(get: { Double(love) }, set: { love = Int($0) }), in: 0...100)
                    .accessibilityLabel(String(localized: "garment_love"))
                    .tint(.pink)
            }
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private func attributeRow<Trailing: View>(
        icon: String,
        title: String,
        value: Int,
        tint: Color,
        @ViewBuilder trailing: () -> Trailing
    ) -> some View {
        HStack(spacing: DS.Spacing.sm) {
            Image(systemName: icon)
                .foregroundStyle(.secondary)
            Text(title)
                .font(.subheadline.weight(.medium))
                .lineLimit(1)
            Spacer(minLength: 0)
            HStack(spacing: 4) {
                ForEach(1...5, id: \.self) { i in
                    Circle()
                        .fill(i <= value ? tint : Color.secondary.opacity(0.2))
                        .frame(width: 8, height: 8)
                }
            }
            trailing()
        }
    }

    private var advancedSection: some View {
        DisclosureGroup(String(localized: "garment_more_options"), isExpanded: $showAdvancedOptions) {
            VStack(alignment: .leading, spacing: DS.Spacing.md) {
                materialPicker

                SingleTagPicker(
                    title: String(localized: "garment_pattern"),
                    allTags: PatternTag.allCases,
                    selectedTag: $patternTag,
                    titleForTag: { $0.title }
                )
            }
            .padding(.top, DS.Spacing.sm)
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
        .onAppear {
            if !scannedMaterials.isEmpty {
                showAdvancedOptions = true
            }
        }
    }

    private var materialPicker: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.xs) {
            Text(String(localized: "garment_materials"))
                .font(.subheadline.weight(.semibold))
                .foregroundStyle(DS.Text.secondary)

            FlowLayout(spacing: 8) {
                ForEach(MaterialTag.allCases) { tag in
                    let selected = scannedMaterials.contains(tag)
                    Button {
                        if let index = scannedMaterials.firstIndex(of: tag) {
                            scannedMaterials.remove(at: index)
                        } else {
                            scannedMaterials.append(tag)
                        }
                        userEditedFields.insert(ItemTypeDefaults.FieldKey.materialTags)
                    } label: {
                        Text(tag.title)
                            .font(.caption.weight(.semibold))
                            .padding(.horizontal, 10)
                            .padding(.vertical, 6)
                            .background(
                                Capsule(style: .continuous)
                                    .fill(selected ? Color.accentColor.opacity(0.18) : Color(.secondarySystemBackground).opacity(0.45))
                            )
                            .overlay(
                                Capsule(style: .continuous)
                                    .strokeBorder(selected ? Color.accentColor.opacity(0.55) : Color.clear, lineWidth: 1)
                            )
                    }
                    .buttonStyle(.plain)
                }
            }
        }
    }

    private var analyzingOverlay: some View {
        VStack(spacing: DS.Spacing.sm) {
            ProgressView()
                .controlSize(.large)
                .tint(.white)
            Text(String(localized: "add_garment_analyzing"))
                .font(.subheadline.weight(.medium))
                .foregroundStyle(.white)
        }
        .padding(DS.Spacing.lg)
        .liquidGlassPill()
    }

    // MARK: - Actions

    private func selectCategory(_ cat: Category) {
        category = cat
        if let current = itemType, !cat.itemTypes.contains(current) {
            itemType = nil
        }
        if cat != .top && cat != .bottom {
            fitTag = nil
        }
        if cat != .top && cat != .bottom && cat != .shoes {
            sizeOption = nil
        } else if let current = sizeOption, !SizeOption.options(for: cat).contains(current) {
            sizeOption = nil
        }
        applyTypeDefaultsToState()
    }

    /// Frictionless path: no crop gate. The picked photo goes straight to
    /// on-device analysis (which also cuts out the background); manual crop
    /// remains available from the hero card for fine-tuning.
    private func processPickedImage(_ image: UIImage) {
        confirmCroppedImage(image, original: image)
    }

    private func lookupProductLink(_ raw: String) {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard ProductPageMetadataService.productPageURL(from: trimmed) != nil else {
            errorMessage = String(localized: "add_garment_paste_link_invalid")
            return
        }
        lookupBarcode(trimmed)
    }

    private func lookupBarcode(_ code: String) {
        let generation = UUID()
        barcodeLookupGeneration = generation
        isLookingUpBarcode = true
        isFetchingProductPage = false
        errorMessage = nil
        // Drop previous scan's photo/fields immediately so they can't leak into the next product.
        clearLookupImageState()
        resetLookupFormFields()

        Task {
            do {
                let product = try await fetchScannedProduct(code)

                // Apply title/brand/category immediately — don't wait on image download.
                await MainActor.run {
                    guard barcodeLookupGeneration == generation else { return }
                    applyBarcodeProduct(product, image: nil)
                    isLookingUpBarcode = false
                    isFetchingProductPage = false
                }

                guard let imageURL = product.imageURL else { return }

                let image = try? await BarcodeLookupService.downloadImage(from: imageURL)
                guard let image else { return }

                await MainActor.run {
                    guard barcodeLookupGeneration == generation else { return }
                    applyProductImage(image)
                    isAnalyzing = true
                }

                let suggestion = await AutoFillService.suggest(from: image)
                await MainActor.run {
                    guard barcodeLookupGeneration == generation else { return }
                    // Only fill gaps — barcode / page metadata wins for brand/title/category.
                    if colorTags.isEmpty, !suggestion.colorTags.isEmpty {
                        colorTags = suggestion.colorTags
                    }
                    if category == nil, let suggestedCategory = suggestion.category {
                        category = suggestedCategory
                    }
                    if itemType == nil, let suggestedType = suggestion.itemType,
                       let cat = category ?? suggestion.category,
                       cat.itemTypes.contains(suggestedType) {
                        itemType = suggestedType
                    }
                    if suggestion.usedCutout {
                        selectedImage = suggestion.displayImage
                        persistDisplayImage(suggestion.displayImage, original: image)
                    }
                    applyTypeDefaultsToState()
                    isAnalyzing = false
                }
            } catch {
                await MainActor.run {
                    guard barcodeLookupGeneration == generation else { return }
                    isLookingUpBarcode = false
                    isFetchingProductPage = false
                    errorMessage = error.localizedDescription
                }
            }
        }
    }

    /// Clears wardrobe photo state from a previous scan / pick.
    private func clearLookupImageState() {
        selectedImage = nil
        originalPickedImage = nil
        pendingCropImage = nil
        savedImagePath = nil
        savedThumbnailPath = nil
        savedOriginalImagePath = nil
        barcodeNeedsPhoto = false
        isAnalyzing = false
    }

    /// Clears product fields so a second barcode doesn't keep the first product's metadata.
    private func resetLookupFormFields() {
        brand = ""
        userTitleOverride = nil
        itemType = nil
        colorTags = []
        sizeOption = nil
        fitTag = nil
        patternTag = nil
        scannedMaterials = []
        labelScanMessage = nil
        didApplyAISuggestions = false
        aiSuggestedCategory = nil
        aiSuggestedItemType = nil
        aiSuggestedColors = []
        aiConfidence = 0
        // Keep planner pre-selection only until the new product applies its own category.
        category = nil
    }

    /// Lined barcodes go to the Barcode Lookup API. Registered `ProductURLResolver`s
    /// (e.g. Digimarc / Ralph Lauren DPIDs) run next. Remaining product-page QR links
    /// scrape Open Graph / JSON-LD. Non-apparel products are rejected before form fill.
    private func fetchScannedProduct(_ code: String) async throws -> BarcodeProduct {
        let product: BarcodeProduct
        if let pageURL = ProductPageMetadataService.productPageURL(from: code) {
            if let resolver = ProductURLResolverRegistry.resolver(for: pageURL) {
                await MainActor.run { isFetchingProductPage = true }
                product = try await resolver.fetch(from: pageURL)
            } else if let explicitCode = BarcodeLookupService.explicitProductCode(fromURL: pageURL),
                      let lookedUp = try? await BarcodeLookupService.lookup(barcode: explicitCode) {
                product = lookedUp
            } else {
                await MainActor.run { isFetchingProductPage = true }
                product = try await ProductPageMetadataService.fetch(url: pageURL)
            }
        } else {
            product = try await BarcodeLookupService.lookup(barcode: code)
        }

        try ProductFieldMapper.requireApparel(product)
        return product
    }

    private func applyBarcodeProduct(_ product: BarcodeProduct, image: UIImage?) {
        // Replace previous scan fields — don't merge leftovers from an earlier barcode.
        brand = product.brand ?? ""
        userTitleOverride = (product.title?.isEmpty == false) ? product.title : nil
        category = product.category
        if let type = product.itemType {
            if let cat = category, cat.itemTypes.contains(type) {
                itemType = type
            } else if category == nil {
                itemType = type
            } else {
                itemType = nil
            }
        } else {
            itemType = nil
        }
        colorTags = product.colors
        sizeOption = product.size
        scannedMaterials = product.materials
        if !product.materials.isEmpty {
            userEditedFields.insert(ItemTypeDefaults.FieldKey.materialTags)
            showAdvancedOptions = true
        }

        didApplyAISuggestions = true
        showAllDetails = true
        applyTypeDefaultsToState()

        if let image {
            applyProductImage(image)
        } else {
            clearLookupImageState()
            barcodeNeedsPhoto = true
            withAnimation(DS.Animation.standard) {
                flowState = .enterDetails
            }
            DS.haptic(0.4)
        }
    }

    private func applyProductImage(_ image: UIImage) {
        barcodeNeedsPhoto = false
        selectedImage = image
        originalPickedImage = image
        persistDisplayImage(image, original: image)
        withAnimation(DS.Animation.standard) {
            flowState = .enterDetails
        }
        DS.haptic(0.5)
    }

    private func reopenCropper() {
        let source = originalPickedImage ?? selectedImage
        guard let source else { return }
        pendingCropImage = source
        showCropper = true
    }

    private func confirmCroppedImage(_ cropped: UIImage, original: UIImage) {
        // Preserve fields already filled from barcode / product-page lookup;
        // AI only fills gaps (see applySuggestion).
        let keepLookupSuggestions = didApplyAISuggestions || barcodeNeedsPhoto
        selectedImage = cropped
        originalPickedImage = original
        barcodeNeedsPhoto = false
        isAnalyzing = true
        if !keepLookupSuggestions {
            didApplyAISuggestions = false
            aiConfidence = 0
            aiSuggestedCategory = nil
            aiSuggestedItemType = nil
            aiSuggestedColors = []
        }

        persistDisplayImage(cropped, original: original)
        withAnimation(DS.Animation.standard) {
            flowState = .enterDetails
        }

        Task {
            let suggestion = await AutoFillService.suggest(from: cropped)
            await MainActor.run {
                applySuggestion(suggestion, original: original)
                if keepLookupSuggestions {
                    didApplyAISuggestions = true
                }
                isAnalyzing = false
            }
        }
    }

    private func persistDisplayImage(_ display: UIImage, original: UIImage) {
        if let jpeg = original.jpegData(compressionQuality: 0.9) {
            savedOriginalImagePath = try? ImageStore.save(data: jpeg, preferredExt: "jpg")
        }
        if let png = display.pngData() {
            savedImagePath = try? ImageStore.save(data: png, preferredExt: "png")
        } else if let jpeg = display.jpegData(compressionQuality: 0.9) {
            savedImagePath = try? ImageStore.save(data: jpeg, preferredExt: "jpg")
        }
        if let path = savedImagePath {
            savedThumbnailPath = ImageStore.generateAndSaveThumbnail(
                for: path,
                maxPixelSize: ImageStore.thumbnailMaxPixelSize
            )
        }
    }

    private func applySuggestion(_ suggestion: AutoFillSuggestion, original: UIImage) {
        selectedImage = suggestion.displayImage
        persistDisplayImage(suggestion.displayImage, original: original)

        aiSuggestedCategory = suggestion.category
        aiSuggestedItemType = suggestion.itemType
        aiSuggestedColors = suggestion.colorTags
        aiConfidence = suggestion.confidence

        var applied = false
        if category == nil, let suggestedCategory = suggestion.category {
            category = suggestedCategory
            applied = true
        }
        if itemType == nil, let suggestedType = suggestion.itemType {
            if let cat = category ?? suggestion.category, cat.itemTypes.contains(suggestedType) {
                itemType = suggestedType
                applied = true
            }
        }
        if colorTags.isEmpty, !suggestion.colorTags.isEmpty {
            colorTags = suggestion.colorTags
            applied = true
        }
        didApplyAISuggestions = applied || suggestion.usedCutout
        applyTypeDefaultsToState()
        if category == nil {
            // AI couldn't classify — open the category card so the one
            // required choice is right in front of the user.
            withAnimation(DS.Animation.standard) {
                focusedSection = .essentials
            }
        }
        if applied {
            DS.haptic(0.4)
        }
    }

    private func handleLabelScan(_ image: UIImage) {
        isScanningLabel = true
        labelScanMessage = nil
        Task {
            let result = await LabelScanService.scan(image: image)
            isScanningLabel = false

            var found: [String] = []
            if let scannedBrand = result.brand, brand.isEmpty {
                brand = scannedBrand
                found.append(scannedBrand)
            }
            if let size = result.size, sizeOption == nil, shouldShowSize,
               let cat = category, SizeOption.options(for: cat).contains(size) {
                sizeOption = size
                found.append(size.title)
            }
            if !result.materials.isEmpty, scannedMaterials.isEmpty {
                scannedMaterials = result.materials
                found.append(result.materials.map(\.title).joined(separator: ", "))
            }

            if found.isEmpty {
                labelScanMessage = String(localized: "label_scan_nothing")
            } else {
                labelScanMessage = String(
                    format: NSLocalizedString("label_scan_found_format", comment: ""),
                    found.joined(separator: " · ")
                )
                DS.haptic(0.5)
            }
        }
    }

    /// Reflect per-type defaults in the visible controls so the chips show
    /// exactly what will be saved. Never touches fields the user edited.
    private func applyTypeDefaultsToState() {
        guard let type = itemType, let defaults = ItemTypeDefaults.defaults(for: type) else { return }
        if !userEditedFields.contains(ItemTypeDefaults.FieldKey.warmth) {
            warmth = defaults.warmth
        }
        if !userEditedFields.contains(ItemTypeDefaults.FieldKey.formality) {
            formality = defaults.formality
        }
        if !userEditedFields.contains(ItemTypeDefaults.FieldKey.season) {
            seasonSuitability = defaults.season
        }
    }

    private func saveGarment() {
        guard let selectedCategory = category else { return }
        guard savedImagePath != nil || selectedImage != nil else {
            errorMessage = String(localized: "edit_image_save_failed")
            return
        }
        // Ensure paths exist even if AI path raced
        if savedImagePath == nil, let selectedImage {
            persistDisplayImage(selectedImage, original: originalPickedImage ?? selectedImage)
        }
        guard savedImagePath != nil else {
            errorMessage = String(localized: "edit_image_save_failed")
            return
        }

        let fitToSave = shouldShowFit ? fitTag : nil
        let sizeToSave = shouldShowSize ? sizeOption : nil

        let garment = Garment(
            category: selectedCategory,
            itemType: itemType,
            brand: brand.isEmpty ? nil : brand.trimmingCharacters(in: .whitespacesAndNewlines),
            colorTags: colorTags,
            userTitleOverride: userTitleOverride,
            patternTag: patternTag,
            fitTag: fitToSave,
            sizeOption: sizeToSave,
            seasonSuitability: seasonSuitability,
            minTempC: minTempC,
            maxTempC: maxTempC,
            warmth: warmth,
            formality: formality,
            loveScore: love,
            imagePath: savedImagePath,
            thumbnailPath: savedThumbnailPath,
            originalImagePath: savedOriginalImagePath,
            aiSuggestedCategory: aiSuggestedCategory,
            aiSuggestedItemType: aiSuggestedItemType,
            aiSuggestedColors: aiSuggestedColors.isEmpty ? nil : aiSuggestedColors,
            aiConfidence: aiConfidence > 0 ? aiConfidence : nil,
            aiProcessedAt: didApplyAISuggestions ? Date() : nil
        )

        if !scannedMaterials.isEmpty {
            // From care label / product QR — treat as verified so AI enrichment won't overwrite.
            garment.materialTags = scannedMaterials
            garment.markUserEdited(ItemTypeDefaults.FieldKey.materialTags)
        }

        if let profile = CurrentUser.activeProfile(in: context, createIfNeeded: true) {
            garment.ownerID = profile.id
            if !profile.garmentIDs.contains(garment.id) {
                profile.garmentIDs.append(garment.id)
            }
        }

        // Provenance: visible fields the user never touched are owned by
        // enrichment (their values came from type defaults), so later AI
        // refinement may improve them.
        var enrichedVisibleFields: [String] = []
        if !userEditedFields.contains(ItemTypeDefaults.FieldKey.warmth) {
            enrichedVisibleFields.append(ItemTypeDefaults.FieldKey.warmth)
        }
        if !userEditedFields.contains(ItemTypeDefaults.FieldKey.formality) {
            enrichedVisibleFields.append(ItemTypeDefaults.FieldKey.formality)
        }
        if !userEditedFields.contains(ItemTypeDefaults.FieldKey.season), garment.seasonSuitability != nil {
            enrichedVisibleFields.append(ItemTypeDefaults.FieldKey.season)
        }
        garment.markEnriched(enrichedVisibleFields)

        garment.thermalWarmthOverride = thermalWarmthOverride
        garment.thermalBreathabilityOverride = thermalBreathabilityOverride

        // Instant offline enrichment for fields the form doesn't expose
        // (layer role, weather/style tags) plus anything still generic.
        GarmentEnrichmentService.applyDefaults(to: garment, userEditedFields: userEditedFields)

        context.insert(garment)

        do {
            try context.save()
            if let path = garment.imagePath {
                CloudKitImageSyncService.shared.enqueueUpload(garmentID: garment.id, imagePath: path)
            }
            if let trimmed = garment.brand, !trimmed.isEmpty {
                BrandStore.upsert(name: trimmed, context: context)
            }
            // On-device AI refinement in the background; respects provenance.
            Task {
                await GarmentEnrichmentService.enrichWithAI(garment, context: context)
            }
            onSave?(garment)
            showSuccess = true
            NotificationCenter.default.post(name: .garmentAdded, object: nil)
        } catch {
            errorMessage = String(
                format: NSLocalizedString("add_garment_save_failed_format", comment: ""),
                error.localizedDescription
            )
        }
    }

    private func resetAndDismiss() {
        category = nil
        itemType = nil
        brand = ""
        colorTags = []
        userTitleOverride = nil
        patternTag = nil
        fitTag = nil
        sizeOption = nil
        seasonSuitability = nil
        minTempC = nil
        maxTempC = nil
        warmth = 3
        thermalWarmthOverride = nil
        thermalBreathabilityOverride = nil
        formality = 3
        love = 50
        selectedImage = nil
        originalPickedImage = nil
        pendingCropImage = nil
        savedImagePath = nil
        savedThumbnailPath = nil
        savedOriginalImagePath = nil
        isAnalyzing = false
        didApplyAISuggestions = false
        aiConfidence = 0
        aiSuggestedCategory = nil
        aiSuggestedItemType = nil
        aiSuggestedColors = []
        userEditedFields = []
        focusedSection = nil
        showAllDetails = false
        batchItems = []
        isSavingBatch = false
        isLookingUpBarcode = false
        isFetchingProductPage = false
        barcodeNeedsPhoto = false
        barcodeLookupGeneration = UUID()
        labelScanMessage = nil
        isScanningLabel = false
        scannedMaterials = []
        flowState = .selectImage
        if onSave != nil {
            dismiss()
        }
    }
}

#Preview {
    AddGarmentView()
}
