import SwiftUI
import SwiftData
import PhotosUI
import UIKit

/// Structured garment capture: pick → crop/edit → details.
struct AddGarmentView: View {
    @Environment(\.modelContext) private var context
    @Environment(\.dismiss) private var dismiss

    @Query(sort: \Brand.name, order: .forward) private var brands: [Brand]

    private enum FlowState: Equatable {
        case selectImage
        case enterDetails
    }

    @State private var flowState: FlowState = .selectImage

    // Structured fields
    @State private var category: Category? = nil
    @State private var itemType: ItemType? = nil
    @State private var brand = ""
    @State private var colorTags: [ColorTag] = []
    @State private var userTitleOverride: String? = nil
    @State private var isEditingTitle = false
    @State private var patternTag: PatternTag? = nil
    @State private var fitTag: FitTag? = nil
    @State private var sizeOption: SizeOption? = nil
    @State private var seasonSuitability: SeasonSuitability? = nil
    @State private var minTempC: Double? = nil
    @State private var maxTempC: Double? = nil
    @State private var warmth = 3
    @State private var formality = 3
    @State private var love = 50

    // Image
    @State private var selectedImage: UIImage?
    @State private var originalPickedImage: UIImage?
    @State private var pendingCropImage: UIImage?
    @State private var showCropper = false
    @State private var savedImagePath: String?
    @State private var savedThumbnailPath: String?
    @State private var savedOriginalImagePath: String?

    // AI
    @State private var isAnalyzing = false
    @State private var aiConfidence: Float = 0
    @State private var didApplyAISuggestions = false
    @State private var aiSuggestedCategory: Category?
    @State private var aiSuggestedItemType: ItemType?
    @State private var aiSuggestedColors: [ColorTag] = []

    // UI
    @State private var showCamera = false
    @State private var showPhotoPicker = false
    @State private var showSuccess = false
    @State private var showAdvancedOptions = false
    @State private var errorMessage: String?

    private let feedback = UIImpactFeedbackGenerator(style: .medium)
    private let onSave: ((Garment) -> Void)?

    init(initialCategory: Category? = nil, onSave: ((Garment) -> Void)? = nil) {
        self.onSave = onSave
        _category = State(initialValue: initialCategory)
    }

    private var autoGeneratedTitle: String {
        var parts: [String] = []
        if let primaryColor = colorTags.first {
            parts.append(primaryColor.title)
        }
        if let type = itemType {
            parts.append(type.title.lowercased())
        } else if let cat = category {
            parts.append(cat.title.lowercased())
        }
        var title = parts.joined(separator: " ")
        if let first = title.first {
            title = first.uppercased() + title.dropFirst()
        }
        if !brand.isEmpty {
            title += " — \(brand)"
        }
        return title.isEmpty ? String(localized: "add_garment_new_item") : title
    }

    private var displayTitle: String {
        if let override = userTitleOverride, !override.isEmpty {
            return override
        }
        return autoGeneratedTitle
    }

    private var canSave: Bool { category != nil }

    private var brandSuggestions: [Brand] {
        let text = brand.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return [] }
        return Array(brands.filter { $0.name.localizedCaseInsensitiveContains(text) }.prefix(5))
    }

    private var shouldShowAddBrand: Bool {
        let text = brand.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return false }
        return !brands.contains(where: { $0.name.lowercased() == text.lowercased() })
    }

    private var shouldShowFit: Bool {
        guard let cat = category else { return false }
        return cat == .top || cat == .bottom
    }

    private var shouldShowSize: Bool {
        guard let cat = category else { return false }
        return cat == .top || cat == .bottom || cat == .shoes
    }

    private var sizeOptions: [SizeOption] {
        guard let cat = category else { return [] }
        return SizeOption.options(for: cat)
    }

    private var categoryColumns: [GridItem] {
        Array(repeating: GridItem(.flexible(minimum: 0), spacing: DS.Spacing.xs), count: 3)
    }

    // MARK: - Body

    var body: some View {
        NavigationStack {
            Group {
                switch flowState {
                case .selectImage:
                    imageSelectionView
                case .enterDetails:
                    detailsFormView
                }
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .navigationTitle(navigationTitle)
            .minimalCollapsingNavBar()
            .withLocalAppBackdrop()
            .toolbar { toolbarContent }
            .alert(String(localized: "add_garment_success_title"), isPresented: $showSuccess) {
                Button(String(localized: "action_done")) { resetAndDismiss() }
            } message: {
                Text(String(localized: "add_garment_success_message"))
            }
            .alert(String(localized: "error_title"), isPresented: Binding(
                get: { errorMessage != nil },
                set: { if !$0 { errorMessage = nil } }
            )) {
                Button(String(localized: "action_confirm"), role: .cancel) {}
            } message: {
                Text(errorMessage ?? String(localized: "error_generic"))
            }
            .sheet(isPresented: $showPhotoPicker) {
                PhotoLibraryPickerWrapper { image in
                    beginCrop(with: image)
                }
            }
            .sheet(isPresented: $showCamera) {
                CameraPickerWrapper { image in
                    beginCrop(with: image)
                }
            }
            .fullScreenCover(isPresented: $showCropper) {
                if let pendingCropImage {
                    ImageCropperView(
                        image: pendingCropImage,
                        initialAspect: .portrait34,
                        onCancel: {
                            showCropper = false
                            self.pendingCropImage = nil
                        },
                        onDone: { cropped in
                            showCropper = false
                            self.pendingCropImage = nil
                            confirmCroppedImage(cropped, original: originalPickedImage ?? cropped)
                        }
                    )
                }
            }
            .onAppear {
                BrandStore.syncFromGarments(context: context)
            }
        }
    }

    private var navigationTitle: String {
        switch flowState {
        case .selectImage: return String(localized: "nav_add_item")
        case .enterDetails: return String(localized: "add_garment_details_title")
        }
    }

    @ToolbarContentBuilder
    private var toolbarContent: some ToolbarContent {
        if flowState == .enterDetails {
            ToolbarItem(placement: .cancellationAction) {
                Button(String(localized: "action_back")) {
                    withAnimation(DS.Animation.standard) {
                        flowState = .selectImage
                    }
                }
            }
            ToolbarItem(placement: .confirmationAction) {
                Button(String(localized: "action_save")) {
                    feedback.impactOccurred(intensity: 1.0)
                    saveGarment()
                }
                .disabled(!canSave)
            }
        }
    }

    // MARK: - Select image

    private var imageSelectionView: some View {
        ZStack {
            VStack(spacing: DS.Spacing.xl) {
                Spacer(minLength: DS.Spacing.lg)

                ZStack {
                    Circle()
                        .fill(Color.accentColor.opacity(0.12))
                        .frame(width: 112, height: 112)
                    Image(systemName: "camera.viewfinder")
                        .font(.system(size: DS.IconSize.xxl, weight: .light))
                        .foregroundStyle(Color.accentColor)
                }

                VStack(spacing: DS.Spacing.sm) {
                    Text(String(localized: "add_garment_hero_title"))
                        .font(.title2.bold())
                        .multilineTextAlignment(.center)
                    Text(String(localized: "add_garment_hero_subtitle"))
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .frame(maxWidth: .infinity)
                .padding(.horizontal, DS.Spacing.md)

                VStack(spacing: DS.Spacing.sm) {
                    Button {
                        DS.haptic(0.6)
                        showCamera = true
                    } label: {
                        Label(String(localized: "add_garment_take_photo"), systemImage: "camera.fill")
                    }
                    .dsPrimaryButton()

                    Button {
                        DS.haptic(0.5)
                        showPhotoPicker = true
                    } label: {
                        Label(String(localized: "add_garment_choose_library"), systemImage: "photo.on.rectangle")
                            .frame(maxWidth: .infinity)
                    }
                    .dsSecondaryButton()
                }
                .frame(maxWidth: .infinity)
                .padding(.horizontal, DS.Spacing.xl)

                Text(String(localized: "add_garment_crop_hint"))
                    .font(.caption)
                    .foregroundStyle(.tertiary)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, DS.Spacing.lg)

                Spacer()
                Spacer()
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .padding(.horizontal, DS.Spacing.md)
        }
    }

    // MARK: - Details

    private var detailsFormView: some View {
        ScrollView {
            VStack(spacing: DS.Spacing.md) {
                heroCard
                essentialsCard
                if shouldShowFit || shouldShowSize {
                    fitSizeSection
                }
                colorSection
                brandSection
                seasonSection
                attributesSection
                advancedSection
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, DS.Spacing.md)
            .padding(.top, DS.Spacing.sm)
            .padding(.bottom, DS.Spacing.xxl)
        }
        .scrollDismissesKeyboard(.interactively)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .safeAreaInset(edge: .bottom, spacing: 0) {
            stickySaveBar
        }
    }

    private var stickySaveBar: some View {
        VStack(spacing: 0) {
            Divider().opacity(0.35)
            Button {
                feedback.impactOccurred(intensity: 1.0)
                saveGarment()
            } label: {
                Text(String(localized: "garment_add_title"))
                    .font(.headline)
                    .frame(maxWidth: .infinity)
            }
            .dsPrimaryButton()
            .disabled(!canSave || isAnalyzing)
            .padding(.horizontal, DS.Spacing.md)
            .padding(.top, DS.Spacing.sm)
            .padding(.bottom, DS.Spacing.md)
        }
        .background(.ultraThinMaterial)
    }

    // MARK: - Cards

    private var heroCard: some View {
        VStack(spacing: DS.Spacing.sm) {
            ZStack {
                RoundedRectangle(cornerRadius: DS.Radius.card, style: .continuous)
                    .fill(Color(.secondarySystemBackground).opacity(0.45))

                if let image = selectedImage {
                    Image(uiImage: image)
                        .resizable()
                        .scaledToFill()
                        .frame(minWidth: 0, maxWidth: .infinity, minHeight: 0, maxHeight: .infinity)
                        .clipped()
                } else {
                    Image(systemName: category?.icon ?? "photo")
                        .font(.system(size: 44, weight: .light))
                        .foregroundStyle(.tertiary)
                }

                if isAnalyzing {
                    Color.black.opacity(0.28)
                    analyzingOverlay
                }
            }
            .aspectRatio(DS.AspectRatio.garmentTile, contentMode: .fit)
            .frame(maxWidth: .infinity)
            .frame(maxHeight: 280)
            .clipShape(RoundedRectangle(cornerRadius: DS.Radius.card, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: DS.Radius.card, style: .continuous)
                    .strokeBorder(Color.white.opacity(0.12), lineWidth: 0.6)
            )

            HStack(spacing: DS.Spacing.sm) {
                Button {
                    reopenCropper()
                } label: {
                    Label(String(localized: "add_garment_edit_photo"), systemImage: "crop")
                        .font(.caption.weight(.semibold))
                }
                .buttonStyle(.plain)

                Button {
                    showCamera = true
                } label: {
                    Label(String(localized: "add_garment_retake"), systemImage: "camera")
                        .font(.caption.weight(.semibold))
                }
                .buttonStyle(.plain)

                Spacer(minLength: 0)

                Button {
                    showPhotoPicker = true
                } label: {
                    Label(String(localized: "add_garment_change_photo"), systemImage: "photo")
                        .font(.caption.weight(.semibold))
                }
                .buttonStyle(.plain)
            }
            .foregroundStyle(.secondary)

            if didApplyAISuggestions {
                Label(String(localized: "add_garment_ai_filled"), systemImage: "sparkles")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .fixedSize(horizontal: false, vertical: true)
            }

            titleEditor
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var titleEditor: some View {
        VStack(spacing: DS.Spacing.xs) {
            if isEditingTitle {
                TextField(String(localized: "garment_edit_title"), text: Binding(
                    get: { userTitleOverride ?? autoGeneratedTitle },
                    set: { userTitleOverride = $0 }
                ))
                .textFieldStyle(.plain)
                .dsFieldStyle()
                .multilineTextAlignment(.center)
                .onSubmit { isEditingTitle = false }

                Button(String(localized: "add_garment_use_auto_title")) {
                    userTitleOverride = nil
                    isEditingTitle = false
                }
                .font(.caption)
                .foregroundStyle(.secondary)
            } else {
                Text(displayTitle)
                    .font(.title3.bold())
                    .multilineTextAlignment(.center)
                    .frame(maxWidth: .infinity)
                    .fixedSize(horizontal: false, vertical: true)

                Button {
                    isEditingTitle = true
                } label: {
                    Label(String(localized: "add_garment_edit_title"), systemImage: "pencil")
                        .font(.caption)
                }
                .foregroundStyle(.secondary)
            }
        }
        .padding(.top, DS.Spacing.xxs)
    }

    private var essentialsCard: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            DSSectionHeader(String(localized: "garment_category"), icon: "square.grid.2x2")

            LazyVGrid(columns: categoryColumns, spacing: DS.Spacing.xs) {
                ForEach(Category.allCases) { cat in
                    Button {
                        feedback.impactOccurred(intensity: 0.5)
                        selectCategory(cat)
                    } label: {
                        VStack(spacing: 6) {
                            Image(systemName: cat.icon)
                                .font(.title3)
                            Text(cat.title)
                                .font(.caption2.weight(.semibold))
                                .lineLimit(1)
                                .minimumScaleFactor(0.8)
                        }
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, DS.Spacing.sm)
                        .foregroundStyle(category == cat ? Color.accentColor : .primary)
                        .background(
                            RoundedRectangle(cornerRadius: DS.Radius.sm, style: .continuous)
                                .fill(category == cat ? Color.accentColor.opacity(0.14) : Color(.secondarySystemBackground).opacity(0.35))
                        )
                        .overlay(
                            RoundedRectangle(cornerRadius: DS.Radius.sm, style: .continuous)
                                .strokeBorder(category == cat ? Color.accentColor.opacity(0.55) : Color.clear, lineWidth: 1)
                        )
                    }
                    .buttonStyle(.plain)
                }
            }

            if let cat = category {
                Text(String(localized: "garment_item_type"))
                    .font(.subheadline.weight(.semibold))
                    .padding(.top, DS.Spacing.xxs)
                ItemTypeSelector(category: cat, selectedType: $itemType)
            }
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var fitSizeSection: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            DSSectionHeader(String(localized: "fit_size_title"), icon: "ruler")
            if shouldShowFit {
                SingleTagPicker(
                    title: String(localized: "fit_label"),
                    allTags: FitTag.allCases,
                    selectedTag: $fitTag,
                    titleForTag: { $0.title }
                )
            }
            if shouldShowSize {
                SingleTagPicker(
                    title: String(localized: "size_label"),
                    allTags: sizeOptions,
                    selectedTag: $sizeOption,
                    titleForTag: { $0.title }
                )
            }
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var colorSection: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            HStack(spacing: DS.Spacing.xs) {
                Image(systemName: "paintpalette")
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(DS.Text.secondary)
                Text(String(localized: "garment_colors"))
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(DS.Text.secondary)
                Spacer(minLength: 0)
                Text(
                    colorTags.isEmpty
                        ? String(localized: "garment_colors_recommended")
                        : String(format: NSLocalizedString("add_garment_colors_selected_format", comment: ""), colorTags.count)
                )
                .font(.caption)
                .foregroundStyle(.secondary)
            }

            ColorTagSelector(selectedColors: $colorTags)

            Text(String(localized: "tag_bilingual_hint"))
                .font(.caption2)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var brandSection: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            DSSectionHeader(String(localized: "garment_brand"), icon: "tag")
            TextField(String(localized: "garment_brand_placeholder"), text: $brand)
                .textFieldStyle(.plain)
                .dsFieldStyle()

            if !brandSuggestions.isEmpty || shouldShowAddBrand {
                VStack(alignment: .leading, spacing: 6) {
                    ForEach(brandSuggestions, id: \.name) { suggestion in
                        Button {
                            brand = suggestion.name
                        } label: {
                            Text(suggestion.name)
                                .font(.caption)
                        }
                        .buttonStyle(.plain)
                    }
                    if shouldShowAddBrand {
                        Text(String(format: NSLocalizedString("brand_add_suggestion", comment: ""), brand))
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            }
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var seasonSection: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.sm) {
            DSSectionHeader(String(localized: "garment_season"), icon: "leaf")
            SeasonSelector(selectedSeason: $seasonSuitability)
            if seasonSuitability != nil {
                DisclosureGroup(String(localized: "garment_temperature_range")) {
                    TemperatureRangeSlider(
                        minTemp: $minTempC,
                        maxTemp: $maxTempC,
                        defaultRange: seasonSuitability?.defaultTempRange ?? (10, 25)
                    )
                }
                .font(.subheadline)
            }
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var attributesSection: some View {
        VStack(alignment: .leading, spacing: DS.Spacing.md) {
            DSSectionHeader(String(localized: "garment_attributes"), icon: "slider.horizontal.3")
            attributeRow(
                icon: "thermometer.medium",
                title: String(localized: "garment_warmth"),
                value: warmth,
                tint: .orange
            ) {
                Stepper("", value: $warmth, in: 1...5)
                    .labelsHidden()
                    .controlSize(.small)
            }
            attributeRow(
                icon: "briefcase",
                title: String(localized: "garment_formality"),
                value: formality,
                tint: .accentColor
            ) {
                Stepper("", value: $formality, in: 1...5)
                    .labelsHidden()
                    .controlSize(.small)
            }
            VStack(alignment: .leading, spacing: DS.Spacing.xs) {
                HStack {
                    Image(systemName: "heart.fill")
                        .foregroundStyle(.pink)
                    Text(String(localized: "garment_love"))
                        .font(.subheadline.weight(.medium))
                    Spacer()
                    Text("\(love)%")
                        .font(.caption.bold())
                        .foregroundStyle(.pink)
                }
                Slider(value: Binding(get: { Double(love) }, set: { love = Int($0) }), in: 0...100)
                    .tint(.pink)
            }
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private func attributeRow<Trailing: View>(
        icon: String,
        title: String,
        value: Int,
        tint: Color,
        @ViewBuilder trailing: () -> Trailing
    ) -> some View {
        HStack(spacing: DS.Spacing.sm) {
            Image(systemName: icon)
                .foregroundStyle(.secondary)
            Text(title)
                .font(.subheadline.weight(.medium))
                .lineLimit(1)
            Spacer(minLength: 0)
            HStack(spacing: 4) {
                ForEach(1...5, id: \.self) { i in
                    Circle()
                        .fill(i <= value ? tint : Color.secondary.opacity(0.2))
                        .frame(width: 8, height: 8)
                }
            }
            trailing()
        }
    }

    private var advancedSection: some View {
        DisclosureGroup(String(localized: "garment_more_options"), isExpanded: $showAdvancedOptions) {
            VStack(alignment: .leading, spacing: DS.Spacing.md) {
                SingleTagPicker(
                    title: String(localized: "garment_pattern"),
                    allTags: PatternTag.allCases,
                    selectedTag: $patternTag,
                    titleForTag: { $0.title }
                )
            }
            .padding(.top, DS.Spacing.sm)
        }
        .padding(DS.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .liquidGlassSurface(cornerRadius: DS.Radius.card, castsShadow: true)
    }

    private var analyzingOverlay: some View {
        VStack(spacing: DS.Spacing.sm) {
            ProgressView()
                .controlSize(.large)
                .tint(.white)
            Text(String(localized: "add_garment_analyzing"))
                .font(.subheadline.weight(.medium))
                .foregroundStyle(.white)
        }
        .padding(DS.Spacing.lg)
        .liquidGlassPill()
    }

    // MARK: - Actions

    private func selectCategory(_ cat: Category) {
        category = cat
        if let current = itemType, !cat.itemTypes.contains(current) {
            itemType = nil
        }
        if cat != .top && cat != .bottom {
            fitTag = nil
        }
        if cat != .top && cat != .bottom && cat != .shoes {
            sizeOption = nil
        } else if let current = sizeOption, !SizeOption.options(for: cat).contains(current) {
            sizeOption = nil
        }
    }

    private func beginCrop(with image: UIImage) {
        originalPickedImage = image
        pendingCropImage = image
        showCropper = true
    }

    private func reopenCropper() {
        let source = originalPickedImage ?? selectedImage
        guard let source else { return }
        pendingCropImage = source
        showCropper = true
    }

    private func confirmCroppedImage(_ cropped: UIImage, original: UIImage) {
        selectedImage = cropped
        originalPickedImage = original
        isAnalyzing = true
        didApplyAISuggestions = false
        aiConfidence = 0
        aiSuggestedCategory = nil
        aiSuggestedItemType = nil
        aiSuggestedColors = []

        persistDisplayImage(cropped, original: original)
        withAnimation(DS.Animation.standard) {
            flowState = .enterDetails
        }

        Task {
            let suggestion = await AutoFillService.suggest(from: cropped)
            await MainActor.run {
                applySuggestion(suggestion, original: original)
                isAnalyzing = false
            }
        }
    }

    private func persistDisplayImage(_ display: UIImage, original: UIImage) {
        if let jpeg = original.jpegData(compressionQuality: 0.9) {
            savedOriginalImagePath = try? ImageStore.save(data: jpeg, preferredExt: "jpg")
        }
        if let png = display.pngData() {
            savedImagePath = try? ImageStore.save(data: png, preferredExt: "png")
        } else if let jpeg = display.jpegData(compressionQuality: 0.9) {
            savedImagePath = try? ImageStore.save(data: jpeg, preferredExt: "jpg")
        }
        if let path = savedImagePath {
            savedThumbnailPath = ImageStore.generateAndSaveThumbnail(
                for: path,
                maxPixelSize: ImageStore.thumbnailMaxPixelSize
            )
        }
    }

    private func applySuggestion(_ suggestion: AutoFillSuggestion, original: UIImage) {
        selectedImage = suggestion.displayImage
        persistDisplayImage(suggestion.displayImage, original: original)

        aiSuggestedCategory = suggestion.category
        aiSuggestedItemType = suggestion.itemType
        aiSuggestedColors = suggestion.colorTags
        aiConfidence = suggestion.confidence

        var applied = false
        if category == nil, let suggestedCategory = suggestion.category {
            category = suggestedCategory
            applied = true
        }
        if itemType == nil, let suggestedType = suggestion.itemType {
            if let cat = category ?? suggestion.category, cat.itemTypes.contains(suggestedType) {
                itemType = suggestedType
                applied = true
            }
        }
        if colorTags.isEmpty, !suggestion.colorTags.isEmpty {
            colorTags = suggestion.colorTags
            applied = true
        }
        didApplyAISuggestions = applied || suggestion.usedCutout
        if applied {
            DS.haptic(0.4)
        }
    }

    private func saveGarment() {
        guard let selectedCategory = category else { return }
        guard savedImagePath != nil || selectedImage != nil else {
            errorMessage = String(localized: "edit_image_save_failed")
            return
        }
        // Ensure paths exist even if AI path raced
        if savedImagePath == nil, let selectedImage {
            persistDisplayImage(selectedImage, original: originalPickedImage ?? selectedImage)
        }
        guard savedImagePath != nil else {
            errorMessage = String(localized: "edit_image_save_failed")
            return
        }

        let fitToSave = shouldShowFit ? fitTag : nil
        let sizeToSave = shouldShowSize ? sizeOption : nil

        let garment = Garment(
            category: selectedCategory,
            itemType: itemType,
            brand: brand.isEmpty ? nil : brand.trimmingCharacters(in: .whitespacesAndNewlines),
            colorTags: colorTags,
            userTitleOverride: userTitleOverride,
            patternTag: patternTag,
            fitTag: fitToSave,
            sizeOption: sizeToSave,
            seasonSuitability: seasonSuitability,
            minTempC: minTempC,
            maxTempC: maxTempC,
            warmth: warmth,
            formality: formality,
            loveScore: love,
            imagePath: savedImagePath,
            thumbnailPath: savedThumbnailPath,
            originalImagePath: savedOriginalImagePath,
            aiSuggestedCategory: aiSuggestedCategory,
            aiSuggestedItemType: aiSuggestedItemType,
            aiSuggestedColors: aiSuggestedColors.isEmpty ? nil : aiSuggestedColors,
            aiConfidence: aiConfidence > 0 ? aiConfidence : nil,
            aiProcessedAt: didApplyAISuggestions ? Date() : nil
        )

        if let profile = CurrentUser.activeProfile(in: context, createIfNeeded: true) {
            garment.ownerID = profile.id
            if !profile.garmentIDs.contains(garment.id) {
                profile.garmentIDs.append(garment.id)
            }
        }

        context.insert(garment)

        do {
            try context.save()
            if let path = garment.imagePath {
                CloudKitImageSyncService.shared.enqueueUpload(garmentID: garment.id, imagePath: path)
            }
            if let trimmed = garment.brand, !trimmed.isEmpty {
                BrandStore.upsert(name: trimmed, context: context)
            }
            onSave?(garment)
            showSuccess = true
            NotificationCenter.default.post(name: .garmentAdded, object: nil)
        } catch {
            errorMessage = String(
                format: NSLocalizedString("add_garment_save_failed_format", comment: ""),
                error.localizedDescription
            )
        }
    }

    private func resetAndDismiss() {
        category = nil
        itemType = nil
        brand = ""
        colorTags = []
        userTitleOverride = nil
        patternTag = nil
        fitTag = nil
        sizeOption = nil
        seasonSuitability = nil
        minTempC = nil
        maxTempC = nil
        warmth = 3
        formality = 3
        love = 50
        selectedImage = nil
        originalPickedImage = nil
        pendingCropImage = nil
        savedImagePath = nil
        savedThumbnailPath = nil
        savedOriginalImagePath = nil
        isAnalyzing = false
        didApplyAISuggestions = false
        aiConfidence = 0
        aiSuggestedCategory = nil
        aiSuggestedItemType = nil
        aiSuggestedColors = []
        flowState = .selectImage
        if onSave != nil {
            dismiss()
        }
    }
}

#Preview {
    AddGarmentView()
}
