import SwiftUI
import SwiftData
import PhotosUI
import UIKit

/// Phase 1: Structured garment capture flow with auto-generated titles.
/// Uses Apple's built-in image editing for reliable crop/rotate.
struct AddGarmentView: View {
    @Environment(\.modelContext) private var context
    @Environment(\.dismiss) private var dismiss
    
    @Query(sort: \Brand.name, order: .forward) private var brands: [Brand]

    // MARK: - Flow State
    
    private enum FlowState {
        case selectImage
        case enterDetails
    }
    
    @State private var flowState: FlowState = .selectImage
    
    // MARK: - Structured Fields
    
    @State private var category: Category? = nil
    @State private var itemType: ItemType? = nil
    @State private var brand = ""
    @State private var colorTags: [ColorTag] = []
    @State private var userTitleOverride: String? = nil
    @State private var isEditingTitle = false
    
    // Optional tags
    @State private var patternTag: PatternTag? = nil
    @State private var fitTag: FitTag? = nil
    @State private var sizeOption: SizeOption? = nil
    @State private var seasonSuitability: SeasonSuitability? = nil
    @State private var minTempC: Double? = nil
    @State private var maxTempC: Double? = nil
    
    // Attributes
    @State private var warmth = 3
    @State private var formality = 3
    @State private var love = 50
    
    // MARK: - Image State
    
    @State private var selectedImage: UIImage?
    @State private var savedImagePath: String?
    @State private var savedThumbnailPath: String?
    
    // MARK: - UI State
    
    @State private var showCamera = false
    @State private var showPhotoPicker = false
    @State private var showSuccess = false
    @State private var showAdvancedOptions = false
    @State private var errorMessage: String?
    
    private let feedback = UIImpactFeedbackGenerator(style: .medium)
    private let onSave: ((Garment) -> Void)?

    // MARK: - Init

    init(initialCategory: Category? = nil, onSave: ((Garment) -> Void)? = nil) {
        self.onSave = onSave
        _category = State(initialValue: initialCategory)
        _itemType = State(initialValue: nil)
    }

    // MARK: - Computed
    
    private var autoGeneratedTitle: String {
        var parts: [String] = []
        
        if let primaryColor = colorTags.first {
            parts.append(primaryColor.title)
        }
        
        if let type = itemType {
            parts.append(type.title.lowercased())
        } else if let cat = category {
            parts.append(cat.title.lowercased())
        }
        
        var title = parts.joined(separator: " ")
        if let first = title.first {
            title = first.uppercased() + title.dropFirst()
        }
        
        if !brand.isEmpty {
            title += " — \(brand)"
        }
        
        return title.isEmpty ? "New Item" : title
    }
    
    private var displayTitle: String {
        if let override = userTitleOverride, !override.isEmpty {
            return override
        }
        return autoGeneratedTitle
    }
    
    private var canSave: Bool {
        category != nil  // Colors are recommended but optional
    }

    private var brandSuggestions: [Brand] {
        let text = brand.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return [] }
        return Array(brands.filter { $0.name.localizedCaseInsensitiveContains(text) }.prefix(5))
    }

    private var shouldShowAddBrand: Bool {
        let text = brand.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return false }
        return !brands.contains(where: { $0.name.lowercased() == text.lowercased() })
    }

    private var shouldShowFit: Bool {
        guard let cat = category else { return false }
        return cat == .top || cat == .bottom
    }

    private var shouldShowSize: Bool {
        guard let cat = category else { return false }
        return cat == .top || cat == .bottom || cat == .shoes
    }

    private var sizeOptions: [SizeOption] {
        guard let cat = category else { return [] }
        return SizeOption.options(for: cat)
    }

    // MARK: - Body
    
    var body: some View {
        NavigationStack {
            Group {
                switch flowState {
                case .selectImage:
                    imageSelectionView
                case .enterDetails:
                    detailsFormView
                }
            }
            .navigationTitle(flowState == .selectImage ? "Add Item" : "New Garment")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                if case .enterDetails = flowState {
                    ToolbarItem(placement: .cancellationAction) {
                        Button("Back") {
                            withAnimation { flowState = .selectImage }
                        }
                    }
                }
            }
            .alert("Success", isPresented: $showSuccess) {
                Button("Done") { resetAndDismiss() }
            } message: {
                Text("Garment added to your wardrobe.")
            }
            .alert("Error", isPresented: .init(
                get: { errorMessage != nil },
                set: { if !$0 { errorMessage = nil } }
            )) {
                Button("OK") {}
            } message: {
                Text(errorMessage ?? "Something went wrong.")
            }
            .sheet(isPresented: $showPhotoPicker) {
                PhotoLibraryPickerWrapper { image in
                    handleSelectedImage(image)
                }
            }
            .sheet(isPresented: $showCamera) {
                CameraPickerWrapper { image in
                    handleSelectedImage(image)
                }
            }
            .onAppear {
                BrandStore.syncFromGarments(context: context)
            }
        }
    }
    
    // MARK: - Image Selection View
    
    private var imageSelectionView: some View {
        ZStack {
            VStack(spacing: DS.Spacing.xl) {
                Spacer()
                
                // Icon
                ZStack {
                    Circle()
                        .fill(Color.accentColor.opacity(0.1))
                        .frame(width: 100, height: 100)
                    
                    Image(systemName: "camera.viewfinder")
                        .font(.system(size: DS.IconSize.xxl, weight: .light))
                        .foregroundStyle(Color.accentColor)
                }
                
                // Title & Description
                VStack(spacing: DS.Spacing.xs) {
                    Text("Add to Wardrobe")
                        .font(.title2.bold())
                    
                    Text("Take a photo or choose from library")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                }
                
                // Buttons
                VStack(spacing: DS.Spacing.sm) {
                    Button {
                        DS.haptic(0.6)
                        showCamera = true
                    } label: {
                        Label("Take Photo", systemImage: "camera.fill")
                    }
                    .dsPrimaryButton()
                    
                    Button {
                        DS.haptic(0.5)
                        showPhotoPicker = true
                    } label: {
                        Label("Choose from Library", systemImage: "photo.on.rectangle")
                            .frame(maxWidth: .infinity)
                    }
                    .dsSecondaryButton()
                }
                .padding(.horizontal, DS.Spacing.xxl)
                
                Spacer()
                Spacer()
            }
            .padding(.horizontal, DS.Spacing.lg)
        }
    }
    
    // MARK: - Details Form View
    
    private var detailsFormView: some View {
        ZStack {
            ScrollView {
                VStack(spacing: DS.Spacing.md) {
                    // Image Preview with Title
                    imagePreviewSection
                    
                    // Category Selection
                    categorySection
                    
                    // Item Type (filtered by category)
                    if category != nil {
                        itemTypeSection
                    }

                    if shouldShowFit || shouldShowSize {
                        fitSizeSection
                    }
                    
                    // Colors
                    colorSection
                    
                    // Brand
                    brandSection
                    
                    // Season & Temperature
                    seasonSection
                    
                    // Attributes
                    attributesSection
                    
                    // Advanced Options
                    advancedSection
                    
                    // Save Button
                    saveButton
                }
                .padding(.horizontal, DS.Spacing.md)
                .padding(.top, DS.Spacing.sm)
                .padding(.bottom, 100)
            }
            .scrollDismissesKeyboard(.interactively)
        }
    }
    
    // MARK: - Sections
    
    private var imagePreviewSection: some View {
        VStack(spacing: 12) {
            // Image
            ZStack {
                RoundedRectangle(cornerRadius: 24, style: .continuous)
                    .fill(Color(.systemGray6))
                
                if let image = selectedImage {
                    Image(uiImage: image)
                        .resizable()
                        .scaledToFit()
                        .padding(16)
                } else {
                    Image(systemName: category?.icon ?? "photo")
                        .font(.system(size: 48, weight: .light))
                        .foregroundStyle(.tertiary)
                }
            }
            .aspectRatio(4.0 / 5.0, contentMode: .fit)
            .frame(maxHeight: 240)
            .clipShape(RoundedRectangle(cornerRadius: 24, style: .continuous))
            
            // Auto-generated Title
            VStack(spacing: 4) {
                if isEditingTitle {
                    TextField("Custom title", text: Binding(
                        get: { userTitleOverride ?? autoGeneratedTitle },
                        set: { userTitleOverride = $0 }
                    ))
                    .textFieldStyle(.roundedBorder)
                    .multilineTextAlignment(.center)
                    .onSubmit { isEditingTitle = false }
                    
                    Button("Use Auto Title") {
                        userTitleOverride = nil
                        isEditingTitle = false
                    }
                    .font(.caption)
                    .foregroundColor(.secondary)
                } else {
                    Text(displayTitle)
                        .font(.title3.bold())
                        .multilineTextAlignment(.center)
                    
                    Button {
                        isEditingTitle = true
                    } label: {
                        Label("Edit Title", systemImage: "pencil")
                            .font(.caption)
                    }
                    .foregroundColor(.secondary)
                }
            }
            .padding(.top, 8)
        }
        .liquidGlassSurface(cornerRadius: 20, padding: 16, castsShadow: true)
    }
    
    private var categorySection: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text(String(localized: "garment_category"))
                    .font(.headline)
                Text("*")
                    .foregroundColor(.red)
            }
            
            LiquidGlassGroup(spacing: 10) {
                LazyVGrid(columns: [GridItem(.adaptive(minimum: 80))], spacing: 10) {
                    ForEach(Category.allCases) { cat in
                        Button {
                        feedback.impactOccurred(intensity: 0.5)
                        category = cat
                        // Reset item type when category changes
                        if let current = itemType, !cat.itemTypes.contains(current) {
                            itemType = nil
                        }
                        if cat != .top && cat != .bottom {
                            fitTag = nil
                        }
                        if cat != .top && cat != .bottom && cat != .shoes {
                            sizeOption = nil
                        } else if let current = sizeOption, !SizeOption.options(for: cat).contains(current) {
                            sizeOption = nil
                        }
                        } label: {
                            VStack(spacing: 4) {
                                Image(systemName: cat.icon)
                                    .font(.title2)
                                Text(cat.title)
                                    .font(.caption2.bold())
                            }
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 12)
                            .foregroundStyle(category == cat ? Color.accentColor : .primary)
                            .liquidGlassSurface(
                                cornerRadius: 12,
                                interactive: true,
                                tint: category == cat ? Color.accentColor.opacity(0.16) : nil
                            )
                        }
                        .buttonStyle(.plain)
                    }
                }
            }
        }
        .liquidGlassSurface(cornerRadius: 20, padding: 16, castsShadow: true)
    }
    
    private var itemTypeSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(String(localized: "garment_item_type"))
                .font(.headline)
            
            if let cat = category {
                ItemTypeSelector(category: cat, selectedType: $itemType)
            }
        }
        .liquidGlassSurface(cornerRadius: 20, padding: 16, castsShadow: true)
    }

    private var fitSizeSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(String(localized: "fit_size_title"))
                .font(.headline)

            if shouldShowFit {
                SingleTagPicker(
                    title: String(localized: "fit_label"),
                    allTags: FitTag.allCases,
                    selectedTag: $fitTag,
                    titleForTag: { $0.title }
                )
            }
            
            if shouldShowSize {
                SingleTagPicker(
                    title: String(localized: "size_label"),
                    allTags: sizeOptions,
                    selectedTag: $sizeOption,
                    titleForTag: { $0.title }
                )
            }
        }
        .liquidGlassSurface(cornerRadius: 20, padding: 16, castsShadow: true)
    }
    
    private var colorSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text(String(localized: "garment_colors"))
                    .font(.headline)
                Spacer()
                if !colorTags.isEmpty {
                    Text("\(colorTags.count) selected")
                        .font(.caption)
                        .foregroundColor(.secondary)
                } else {
                    Text(String(localized: "garment_colors_recommended"))
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
            }
            
            ColorTagSelector(selectedColors: $colorTags)
            
            Text(String(localized: "tag_bilingual_hint"))
                .font(.caption2)
                .foregroundStyle(.secondary)
        }
        .liquidGlassSurface(cornerRadius: 20, padding: 16, castsShadow: true)
    }
    
    private var brandSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(String(localized: "garment_brand"))
                .font(.headline)
            
            TextField(String(localized: "garment_brand_placeholder"), text: $brand)
                .textFieldStyle(.roundedBorder)

            if !brandSuggestions.isEmpty || shouldShowAddBrand {
                VStack(alignment: .leading, spacing: 6) {
                    ForEach(brandSuggestions, id: \.name) { suggestion in
                        Button {
                            brand = suggestion.name
                        } label: {
                            Text(suggestion.name)
                                .font(.caption)
                        }
                        .buttonStyle(.plain)
                    }

                    if shouldShowAddBrand {
                        Button {
                            // Keep the typed brand
                        } label: {
                            Text(String(format: NSLocalizedString("brand_add_suggestion", comment: ""), brand))
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                        .buttonStyle(.plain)
                    }
                }
            }
        }
        .liquidGlassSurface(cornerRadius: 20, padding: 16, castsShadow: true)
    }
    
    private var seasonSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(String(localized: "garment_season"))
                .font(.headline)
            
            SeasonSelector(selectedSeason: $seasonSuitability)
            
            if seasonSuitability != nil {
                DisclosureGroup(String(localized: "garment_temperature_range")) {
                    TemperatureRangeSlider(
                        minTemp: $minTempC,
                        maxTemp: $maxTempC,
                        defaultRange: seasonSuitability?.defaultTempRange ?? (10, 25)
                    )
                }
                .font(.subheadline)
            }
        }
        .liquidGlassSurface(cornerRadius: 20, padding: 16, castsShadow: true)
    }
    
    private var attributesSection: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text(String(localized: "garment_attributes"))
                .font(.headline)
            
            // Warmth
            HStack {
                Image(systemName: "thermometer.medium")
                    .foregroundStyle(.secondary)
                Text(String(localized: "garment_warmth"))
                    .font(.subheadline.weight(.medium))
                Spacer()
                HStack(spacing: 4) {
                    ForEach(1...5, id: \.self) { i in
                        Circle()
                            .fill(i <= warmth ? Color.orange : Color.secondary.opacity(0.2))
                            .frame(width: 8, height: 8)
                    }
                }
                Stepper("", value: $warmth, in: 1...5)
                    .labelsHidden()
                    .controlSize(.small)
            }
            
            // Formality
            HStack {
                Image(systemName: "briefcase")
                    .foregroundStyle(.secondary)
                Text(String(localized: "garment_formality"))
                    .font(.subheadline.weight(.medium))
                Spacer()
                HStack(spacing: 4) {
                    ForEach(1...5, id: \.self) { i in
                        Circle()
                            .fill(i <= formality ? Color.accentColor : Color.secondary.opacity(0.2))
                            .frame(width: 8, height: 8)
                    }
                }
                Stepper("", value: $formality, in: 1...5)
                    .labelsHidden()
                    .controlSize(.small)
            }
            
            // Love
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    Image(systemName: "heart.fill")
                        .foregroundColor(.pink)
                    Text(String(localized: "garment_love"))
                        .font(.subheadline.weight(.medium))
                    Spacer()
                    Text("\(love)%")
                        .font(.caption.bold())
                        .foregroundColor(.pink)
                }
                Slider(value: .init(get: { Double(love) }, set: { love = Int($0) }), in: 0...100)
                    .tint(.pink)
            }
        }
        .liquidGlassSurface(cornerRadius: 20, padding: 16, castsShadow: true)
    }
    
    private var advancedSection: some View {
        DisclosureGroup(String(localized: "garment_more_options"), isExpanded: $showAdvancedOptions) {
            VStack(alignment: .leading, spacing: 16) {
                SingleTagPicker(
                    title: String(localized: "garment_pattern"),
                    allTags: PatternTag.allCases,
                    selectedTag: $patternTag,
                    titleForTag: { $0.title }
                )
            }
            .padding(.top, 12)
        }
        .liquidGlassSurface(cornerRadius: 20, padding: 16, castsShadow: true)
    }
    
    private var saveButton: some View {
        Button {
            feedback.impactOccurred(intensity: 1.0)
            saveGarment()
        } label: {
            Text(String(localized: "garment_add_title"))
                .font(.headline)
                .frame(maxWidth: .infinity)
        }
        .dsPrimaryButton()
        .disabled(!canSave)
    }
    
    // MARK: - Actions
    
    private func handleSelectedImage(_ image: UIImage) {
        selectedImage = image
        
        if let jpeg = image.jpegData(compressionQuality: 0.9) {
            savedImagePath = try? ImageStore.save(data: jpeg, preferredExt: "jpg")
            if let path = savedImagePath {
                savedThumbnailPath = ImageStore.generateAndSaveThumbnail(
                    for: path,
                    maxPixelSize: ImageStore.thumbnailMaxPixelSize
                )
            }
        }
        
        withAnimation { flowState = .enterDetails }
    }
    
    private func saveGarment() {
        guard let selectedCategory = category else { return }
        
        let fitToSave = shouldShowFit ? fitTag : nil
        let sizeToSave = shouldShowSize ? sizeOption : nil

        let garment = Garment(
            category: selectedCategory,
            itemType: itemType,
            brand: brand.isEmpty ? nil : brand.trimmingCharacters(in: .whitespacesAndNewlines),
            colorTags: colorTags,
            userTitleOverride: userTitleOverride,
            patternTag: patternTag,
            fitTag: fitToSave,
            sizeOption: sizeToSave,
            seasonSuitability: seasonSuitability,
            minTempC: minTempC,
            maxTempC: maxTempC,
            warmth: warmth,
            formality: formality,
            loveScore: love,
            imagePath: savedImagePath,
            thumbnailPath: savedThumbnailPath
        )
        
        // Assign owner (MVP: use first profile if available)
        let desc = FetchDescriptor<UserProfile>()
        if let profile = (try? context.fetch(desc))?.first {
            garment.ownerID = profile.id
            if !profile.garmentIDs.contains(garment.id) {
                profile.garmentIDs.append(garment.id)
            }
        }
        
        context.insert(garment)
        
        do {
            try context.save()
            if let path = garment.imagePath {
                CloudKitImageSyncService.shared.enqueueUpload(garmentID: garment.id, imagePath: path)
            }
            if let trimmed = garment.brand, !trimmed.isEmpty {
                BrandStore.upsert(name: trimmed, context: context)
            }
            onSave?(garment)
            showSuccess = true
            NotificationCenter.default.post(name: .garmentAdded, object: nil)
        } catch {
            errorMessage = "Failed to save: \(error.localizedDescription)"
        }
    }
    
    private func resetAndDismiss() {
        category = nil
        itemType = nil
        brand = ""
        colorTags = []
        userTitleOverride = nil
        patternTag = nil
        fitTag = nil
        sizeOption = nil
        seasonSuitability = nil
        minTempC = nil
        maxTempC = nil
        warmth = 3
        formality = 3
        love = 50
        selectedImage = nil
        savedImagePath = nil
        savedThumbnailPath = nil
        flowState = .selectImage
    }
}

#Preview {
    AddGarmentView()
}
