import Foundation
import SwiftData
import UIKit

@Model
final class Garment {
    // MARK: - Identity
    var id: UUID = Foundation.UUID()

    // MARK: - Core Classification (Structured)
    var category: Category = Category.top
    var itemType: ItemType?
    var brand: String?
    
    // MARK: - Color Tags (Multi-select)
    /// New structured color tags. Optional for migration compatibility.
    var colorTags: [ColorTag]?
    
    // MARK: - Legacy Fields (for backward compatibility)
    /// Legacy name field - migrated to userTitleOverride
    var legacyName: String?
    /// Legacy colors as strings
    var legacyColors: [String]?
    
    // MARK: - Title System
    /// User-provided title override. If set, this is displayed instead of auto-generated title.
    var userTitleOverride: String?
    
    // MARK: - Optional Tags
    var materialTags: [MaterialTag]?
    var patternTag: PatternTag?
    var styleTags: [StyleTag]?
    var fitTag: FitTag?
    var sizeOption: SizeOption?
    var layerRole: LayerRole?
    var weatherTags: [WeatherSuitability]?
    var occasionTags: [OccasionTag]?
    
    // MARK: - Season & Temperature
    var seasonSuitability: SeasonSuitability?
    var minTempC: Double?
    var maxTempC: Double?

    // MARK: - Attributes (User-rated)
    var warmth: Int = 3          // 1..5
    var formality: Int = 3       // 1..5
    var loveScore: Int = 50      // 0..100

    // MARK: - Image Storage
    var imagePath: String?
    var thumbnailPath: String?
    var originalImagePath: String?
    var additionalImagePaths: [String]?
    var imageData: Data?  // Legacy

    // MARK: - AI Metadata (Phase 3 - unused in Phase 1)
    var aiSuggestedCategory: Category?
    var aiSuggestedItemType: ItemType?
    var aiSuggestedColors: [ColorTag]?
    var aiConfidence: Float?
    var aiProcessedAt: Date?

    // MARK: - Usage/Meta
    var isFavorite: Bool = false
    var isWorn: Bool = false
    var lastWorn: Date?
    var timesWorn: Int = 0
    var isBlocked: Bool = false
    var unavailableUntil: Date?
    var createdAt: Date?
    var notes: String?
    
    // MARK: - Migration Flag
    var migrationVersion: Int?

    // MARK: - Ownership
    var ownerID: UUID? = nil
    var outfitIDs: [UUID] = []
    /// Legacy (migration-only): stored outfit IDs as strings
    var outfitIDStrings: [String] = []

    // MARK: - Computed Properties
    
    /// Safe accessor for colorTags that handles nil (legacy data)
    @Transient
    var safeColorTags: [ColorTag] {
        get {
            if let tags = colorTags, !tags.isEmpty {
                return tags
            }
            // Try to convert legacy colors
            if let legacy = legacyColors {
                return legacy.compactMap { colorString in
                    ColorTag.allCases.first { $0.title.lowercased() == colorString.lowercased() }
                }
            }
            return []
        }
        set {
            colorTags = newValue
        }
    }
    
    /// The display title for this garment
    @Transient
    var displayTitle: String {
        // 1. Check for explicit user override
        if let override = userTitleOverride, !override.isEmpty {
            return override
        }
        // 2. Check for legacy name (from old data)
        if let legacy = legacyName, !legacy.isEmpty {
            return legacy
        }
        // 3. Generate title from structured fields
        return autoGeneratedTitle
    }
    
    /// Auto-generated title based on structured fields
    @Transient
    var autoGeneratedTitle: String {
        var parts: [String] = []
        
        // 1. Primary color
        if let primaryColor = safeColorTags.first {
            parts.append(primaryColor.title)
        }
        
        // 2. Item type (or category fallback)
        if let type = itemType {
            parts.append(type.title.lowercased())
        } else {
            parts.append(category.title.lowercased())
        }
        
        // Join color + type
        var title = parts.joined(separator: " ")
        
        // Capitalize first letter
        if let first = title.first {
            title = first.uppercased() + title.dropFirst()
        }
        
        // 3. Brand suffix
        if let brand = brand, !brand.isEmpty {
            title += " — \(brand)"
        }
        
        // Fallback if completely empty
        if title.trimmingCharacters(in: .whitespaces).isEmpty {
            return "Garment"
        }
        
        return title
    }
    
    /// Legacy name accessor for backward compatibility
    @Transient
    var name: String {
        get { displayTitle }
        set {
            userTitleOverride = newValue
            // Clear legacy name once user explicitly sets a new name
            legacyName = nil
        }
    }
    
    /// Legacy colors accessor (converts string array to/from ColorTags)
    @Transient
    var colors: [String] {
        get { safeColorTags.map { $0.title.lowercased() } }
        set {
            colorTags = newValue.compactMap { colorString in
                ColorTag.allCases.first { $0.title.lowercased() == colorString.lowercased() }
            }
            // Also store as legacy for safety
            legacyColors = newValue
        }
    }

    @Transient
    var resolvedImage: UIImage? {
        if let p = imagePath, let img = ImageStore.loadImage(path: p) { return img }
        if let d = imageData { return UIImage(data: d) }
        return nil
    }
    
    /// Effective temperature range (user-set or default from warmth)
    @Transient
    var effectiveTempRange: (min: Double, max: Double) {
        if let min = minTempC, let max = maxTempC {
            return (min, max)
        }
        // Default based on warmth (always works, even for legacy data)
        return Self.defaultTempRange(forWarmth: warmth)
    }
    
    /// Check if garment is suitable for a given temperature
    func isSuitableFor(temperature: Double) -> Bool {
        let range = effectiveTempRange
        return temperature >= range.min && temperature <= range.max
    }
    
    /// Default temperature ranges based on warmth level
    static func defaultTempRange(forWarmth warmth: Int) -> (min: Double, max: Double) {
        switch warmth {
        case 1: return (22, 40)   // Very light - hot weather
        case 2: return (18, 30)   // Light
        case 3: return (12, 24)   // Medium
        case 4: return (5, 18)    // Warm
        case 5: return (-5, 12)   // Very warm - cold weather
        default: return (10, 25)
        }
    }
    
    /// Check if this garment needs migration
    @Transient
    var needsMigration: Bool {
        migrationVersion == nil || migrationVersion! < 2
    }
    
    /// Check if garment is currently unavailable (blocked or temporarily unavailable)
    @Transient
    var isCurrentlyUnavailable: Bool {
        if isBlocked { return true }
        if let until = unavailableUntil, until > Date() { return true }
        return false
    }
    
    /// Mark garment as unavailable
    func markUnavailable(until: Date? = nil, reason: String? = nil) {
        if let until = until {
            unavailableUntil = until
        } else {
            isBlocked = true
        }
        if let reason = reason {
            notes = (notes ?? "") + "\n[Unavailable: \(reason)]"
        }
    }
    
    /// Mark garment as available again
    func markAvailable() {
        isBlocked = false
        unavailableUntil = nil
    }
    
    /// Perform one-time migration of legacy fields
    func migrateIfNeeded() {
        guard needsMigration else { return }
        
        // Migrate legacy colors to colorTags
        if colorTags == nil || colorTags!.isEmpty {
            if let legacy = legacyColors, !legacy.isEmpty {
                colorTags = legacy.compactMap { colorString in
                    ColorTag.allCases.first { $0.title.lowercased() == colorString.lowercased() }
                }
            }
        }
        
        // Auto-derive season from warmth if not set
        if seasonSuitability == nil {
            switch warmth {
            case 1...2: seasonSuitability = .summer
            case 3: seasonSuitability = .transitional
            case 4...5: seasonSuitability = .winter
            default: seasonSuitability = .allSeason
            }
        }
        
        migrationVersion = 2
    }

    // MARK: - Init
    init(
        id: UUID? = nil,
        category: Category? = nil,
        itemType: ItemType? = nil,
        brand: String? = nil,
        colorTags: [ColorTag]? = nil,
        legacyName: String? = nil,
        legacyColors: [String]? = nil,
        userTitleOverride: String? = nil,
        materialTags: [MaterialTag]? = nil,
        patternTag: PatternTag? = nil,
        styleTags: [StyleTag]? = nil,
        fitTag: FitTag? = nil,
        sizeOption: SizeOption? = nil,
        layerRole: LayerRole? = nil,
        weatherTags: [WeatherSuitability]? = nil,
        occasionTags: [OccasionTag]? = nil,
        seasonSuitability: SeasonSuitability? = nil,
        minTempC: Double? = nil,
        maxTempC: Double? = nil,
        warmth: Int = 3,
        formality: Int = 3,
        loveScore: Int = 50,
        imagePath: String? = nil,
        thumbnailPath: String? = nil,
        originalImagePath: String? = nil,
        additionalImagePaths: [String]? = nil,
        imageData: Data? = nil,
        aiSuggestedCategory: Category? = nil,
        aiSuggestedItemType: ItemType? = nil,
        aiSuggestedColors: [ColorTag]? = nil,
        aiConfidence: Float? = nil,
        aiProcessedAt: Date? = nil,
        isFavorite: Bool = false,
        isWorn: Bool = false,
        lastWorn: Date? = nil,
        timesWorn: Int = 0,
        isBlocked: Bool = false,
        unavailableUntil: Date? = nil,
        createdAt: Date? = nil,
        notes: String? = nil,
        migrationVersion: Int? = 2,
        ownerID: UUID? = nil,
        outfitIDs: [UUID] = [],
        legacyOutfitIDStrings: [String] = []
    ) {
        self.id = id ?? Foundation.UUID()
        self.category = category ?? Category.top
        self.itemType = itemType
        self.brand = brand
        self.colorTags = colorTags
        self.legacyName = legacyName
        self.legacyColors = legacyColors
        self.userTitleOverride = userTitleOverride
        self.materialTags = materialTags
        self.patternTag = patternTag
        self.styleTags = styleTags
        self.fitTag = fitTag
        self.sizeOption = sizeOption
        self.layerRole = layerRole
        self.weatherTags = weatherTags
        self.occasionTags = occasionTags
        self.seasonSuitability = seasonSuitability
        self.minTempC = minTempC
        self.maxTempC = maxTempC
        self.warmth = warmth
        self.formality = formality
        self.loveScore = loveScore
        self.imagePath = imagePath
        self.thumbnailPath = thumbnailPath
        self.originalImagePath = originalImagePath
        self.additionalImagePaths = additionalImagePaths
        self.imageData = imageData
        self.aiSuggestedCategory = aiSuggestedCategory
        self.aiSuggestedItemType = aiSuggestedItemType
        self.aiSuggestedColors = aiSuggestedColors
        self.aiConfidence = aiConfidence
        self.aiProcessedAt = aiProcessedAt
        self.isFavorite = isFavorite
        self.isWorn = isWorn
        self.lastWorn = lastWorn
        self.timesWorn = timesWorn
        self.isBlocked = isBlocked
        self.unavailableUntil = unavailableUntil
        self.createdAt = createdAt ?? Foundation.Date()
        self.notes = notes
        self.migrationVersion = migrationVersion
        self.ownerID = ownerID
        self.outfitIDs = outfitIDs
        self.outfitIDStrings = legacyOutfitIDStrings
    }
}
