#!/usr/bin/env python3
"""Builds docs/privacy-policy.html (served by GitHub Pages) from the app's privacy strings,
so the App Store privacy policy URL shows the same text as Settings > Your data > Privacy policy.
Run from the repo root after changing any privacy_* string: python3 scripts/make_privacy_page.py"""
import html
import re

SECTIONS = ["summary", "stored", "leaves", "permissions", "signin", "choices", "children", "contact"]
LANGS = [("en", "ltr", "English"), ("he", "rtl", "עברית")]


def load(lang):
    text = open(f"WearIt/{lang}.lproj/Localizable.strings", encoding="utf-8").read()
    pairs = re.findall(r'^"(privacy_[^"]+)" = "((?:[^"\\]|\\.)*)";$', text, re.M)
    return {key: value.replace('\\"', '"') for key, value in pairs}


def linkify(text):
    escaped = html.escape(text)
    return re.sub(r"([\w.+-]+@[\w-]+\.[\w.]+)", r'<a href="mailto:\1">\1</a>', escaped)


parts = []
for lang, direction, label in LANGS:
    strings = load(lang)
    parts.append(f'<section lang="{lang}" dir="{direction}" id="{lang}">')
    parts.append(f"<h2>{html.escape(strings['privacy_title'])}</h2>")
    parts.append(f'<p class="date">{html.escape(strings["privacy_effective_date"])}</p>')
    for name in SECTIONS:
        parts.append(f"<h3>{html.escape(strings[f'privacy_section_{name}_title'])}</h3>")
        parts.append(f"<p>{linkify(strings[f'privacy_section_{name}_body'])}</p>")
    parts.append("</section>")

page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>WearIt privacy policy</title>
<!-- Generated by scripts/make_privacy_page.py from the app's Localizable.strings. Do not edit by hand. -->
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font: 16px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif; max-width: 720px; margin: 0 auto; padding: 24px 16px 48px; }}
  h1 {{ font-size: 28px; margin-bottom: 4px; }}
  nav a {{ margin-inline-end: 16px; }}
  section {{ margin-top: 32px; }}
  h3 {{ margin-bottom: 4px; }}
  p {{ margin-top: 0; }}
  .date {{ opacity: 0.7; font-size: 14px; }}
</style>
</head>
<body>
<h1>WearIt</h1>
<nav><a href="#en">English</a><a href="#he">עברית</a></nav>
{chr(10).join(parts)}
</body>
</html>
"""
open("docs/privacy-policy.html", "w", encoding="utf-8").write(page)
print("wrote docs/privacy-policy.html")
